### ISSUE TITLE
Add option to calculate distance/time from last stop.

### ISSUE THREAD

**Issue by alecava58** [itinero/routing#10]
It would be useful if, after the routing calculation (route.calculate), the collection Stops would report the distance/time from the preceding stop.

Alessandro

**Comment by xivk** [comment]
You can calculate this by getting the shape point at the stop and the one at the previous stop and subtracting associated distance/time in the meta objects. But thanks for you suggestion. It may be a good idea to add this code by default. Leaving this issue open...

**Comment by xivk** [comment]
@alecava58 I added time/distance by default, you can get the time/distance to previous now by substracting the two...
