### ISSUE TITLE
 Example on ASP.NET MVC

### ISSUE THREAD

**Issue by JenyaIkonnikov** [itinero/routing#113]
Hello, I wrote you in the mail. And I ask here. Please write an example of building routing in ASP.NET MVC 5. If I learn to use your library, something will work out in my life

**Comment by xivk** [comment]
There is a very basic web-api implemented here, it uses Nancy, you should be able to do the same in ASP.NET:

https://github.com/itinero/routing-api

**Comment by ironromeo** [comment]
I tried to setup your demo with Nancy but have got error. Please se my issue "[demo url cause error #2](https://github.com/itinero/routing-api/issues/2)"
