### ISSUE TITLE
Location not found when calculating time matrix

### ISSUE THREAD

**Issue by arielmoraes** [itinero/routing#114]
Hello, I'm testing the time/distance matrix with some coordinates from my city, but when using these points expecting a time matrix result, a message saying the point was not found is returned instead by using `Vehicle.Car.Fastest()`. When using `Vehicle.Car.Shortest()` the distances are returned as expected.

I've implemented the way that is described in the wiki. Am I missing something?

Thank you.

**Comment by xivk** [comment]
Did you see this part of the docs:

https://github.com/itinero/routing/wiki/Matrix-Calculations#error-handling

If yes, can you post a code-snippet and the locations causing the problem?

**Comment by arielmoraes** [comment]
Yes, I used the same code as described in the docs. I'm not at home now and when I arrive I'll post the locations, but the only change I've made to the code was changing the `Vehicle.Car.Fastest()` to `Vehicle.Car.Shortest()`.

**Comment by xivk** [comment]
@arielmoraes Any updates? I'm interested in all issues, they usually improve code quality or docs.

**Comment by xivk** [comment]
Assuming this is related to #116, closing.
