### ISSUE TITLE
Resolving point on network

### ISSUE THREAD

**Issue by t22dk** [itinero/routing#118]
I am having some problems calculating routes, where one of the point is not close to a road.

I am using this
var point = router.Resolve(profile, Coords[i].Coordinate, 3000f);
But it seems that it returns no error, but the point that is returns is the same as the input coordinate. (My guess is that it should return the closest point on the network ?)

It's properly  just me, but i can't seem to get the resolved point out of the function.

When i pass the point to a router, it can't calculate a path, since it uses a search buffer of something like 50 meters.

What am I doing wrong  :-)

**Comment by xivk** [comment]
Ah, the resolved point keeps the original **and** the location on the network by keeping the edgeid and offset. You can get the coordinate on the network via this method:

https://github.com/itinero/routing/blob/develop/src/Itinero/RouterPointExtensions.cs#L256

You should pass the routerpoint response from ```var point = router.Resolve(profile, Coords[i].Coordinate, 3000f);``` to the routing method using this:

https://github.com/itinero/routing/blob/develop/src/Itinero/RouterBaseExtensions.cs#L387

**Comment by t22dk** [comment]
Arhh, thanks.

Thats was what i was missing.

In earlier versions, the point returned, was the LocationOnNetwork point.

Now its working fine, thanks.

**Comment by xivk** [comment]
Yes, that behaviour did change before 1.0, sorry. The old behaviour was a bug.
