### ISSUE TITLE
Real-time Restrictions

### ISSUE THREAD

**Issue by jerryfaust** [itinero/routing#119]
Hello.  I've just started using Itinero and I am very excited about what the library can do.  We have a need for real-time barriers to routes, such as a closed road or restricted access to an Incident Perimeter.  I think I'm supposed to add Restrictions.  For a Road Closure, I am capturing a mouse click near a street, and using RouterBaseExtensions.TryResolve to get a nearest Edge of the network.  From the edge I can get the From and To vertices.  I then added these to a RestrictionsDb, then added the RestrictionsDb to my RouterDb, and re-Calculated the route.  However, I get inconsistent results.  Sometimes it appears to re-route around that Edge, but more often, it does not.  Am I doing this incorrectly?  And if you could steer me in the right direction, how should I restrict access to specific edges, or keep vehicles from entering Polygons?  Thanks for any help!

**Comment by xivk** [comment]
Something like this isn't supported at the moment but it is on the roadmap:

https://github.com/itinero/routing/wiki/Roadmap#version-20-and-beyond

It was a good idea to try this based on the restrictions but that's not always going to work well, as you suggest. The restriction code assumes that a restrictions is either just one vertex, think a barrier, or three, a restricted turn.

You could try and add the vertices individually, simulate barriers, and see if that works but I'm not sure what the effect would be and routing would still be possible on the edge between.

We do offer support, and we implement features on-demand too, if you want to, but for now this is what there is.

**Comment by jerryfaust** [comment]
Thank you for the reply.  Is there an estimated timeframe for the 2.0 release?

**Comment by xivk** [comment]
There is now a plan to implement this, we'll start in the next couple of weeks, expect results end of first quarter of 2018.

http://docs.itinero.tech/docs/itinero/development/features/2017-11-16-customizable-ch.html

Closing this as it is part of the development plan.

**Comment by jerryfaust** [comment]
@xivk Is there any progress on this issue (related to #92)?  If there is a branch out there, I can do some testing.  Thank you.  Respectfully.
