### ISSUE TITLE
Cannot install Itinero.IO.Osm in .NET Core project.

### ISSUE THREAD

**Issue by xivk** [itinero/routing#12]
The Itinero.IO.Osm project cannot be install in a .NET Core project because of the range specified for the OsmSharp.Core dependency:

https://github.com/itinero/routing/blob/develop/nuspec/Itinero.IO.Osm.nuspec#L18

Update this to the min .NET Core compat version of OsmSharp.Core.

**Comment by kevin-work** [comment]
This seems to be failing again but with a different error:

```error NU1002: The dependency Reminiscence 1.0.2 does not support framework .NETCoreApp,Version=v1.0```
