### ISSUE TITLE
System.IndexOutOfRangeException at Itinero.Result`1.get_Value() using contracted routerdb

### ISSUE THREAD

**Issue by Chaz6** [itinero/routing#121]
My code works correctly using a normal (uncontracted) routerdb however if I try using a contracted routerdb I get the error. I am using Itinero Api 1.3.0.

Sample code:-

```
RouterDb routerDb;
using (var stream = File.OpenRead("england-latest.osm.pbf.V6.contracted.routerdb"))
{
   routerDb = RouterDb.Deserialize(stream);
}

var router = new Router(routerDb);
var locations = new Coordinate[]
{
   new Coordinate(52.3765626f,1.0870472f),
   new Coordinate(52.4444338f,1.6901452f)
};
var resolvedLocations = router.Resolve(Vehicle.Car.Fastest(), locations);
var invalids = new HashSet<int>();
var weights = router.CalculateWeight(Vehicle.Car.Fastest(),
   resolvedLocations, invalids);
			   
for (var i = 0; i < resolvedLocations.Length; i++)
{
	Console.WriteLine(string.Format("Coordinate {0},{1}", resolvedLocations[i].Latitude, resolvedLocations[i].Longitude));
}
			
var route = router.Calculate(Vehicle.Car.Fastest(), resolvedLocations);
var routeJson = route.ToGeoJson();
Console.WriteLine(routeJson);
```

This is the error:-
```
Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Itinero.Result`1.get_Value()
```

I generated the routerdb using http://files.itinero.tech/builds/idp/idp-2.13.1-win8-x64.zip on Windows 7 64bit.

**Comment by Chaz6** [comment]
I get the same error if I create the contracted db within the codebase. If it helps, I am using the .Net Core SDK to build my program.

```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Users\chaz6\dotnet-dev-win-x64.1.0.4\sdk\1.0.4
```

**Comment by xivk** [comment]
FYI: Checking this issue now. Thanks for reporting.

**Comment by xivk** [comment]
I get this route:

http://geojson.io/#id=gist:anonymous/d835fbc8a390797358d65c7b19e0123c&map=11/52.4432/1.4117

Can you show me the line this is happening on? What is the end goal of your code, maybe I can given some pointers?

Are all points properly resolved?

**Comment by Chaz6** [comment]
I don't know what I did but I've gone back and it's now working! Once it's done, hopefully I will have a useful project to share. Sorry for the noise.

**Comment by xivk** [comment]
No worries, It's always good when people submit issues, it improves the project every time! 👍 

And yes, please let me know if you have something to share... :-)
