### ISSUE TITLE
[Bug?] ContractedNeighbours Always 1?

### ISSUE THREAD

**Issue by airbreather** [itinero/routing#125]
I was looking through the code for the "new" edge-based stuff, and [this line](https://github.com/itinero/routing/blob/ca708b01ee45085cf3a90bbab9be2eee51a0b91b/src/Itinero/Algorithms/Contracted/Dual/HierarchyBuilder.cs#L452) caught my eye...

Since `count++` always returns the original value of `count`, is it a problem that this effectively means that the value in that dictionary is always just 1?

**Comment by xivk** [comment]
Hmm, interesting thanks! That shouldn't really affect the correctness of the contraction but could affect performance.

Will try and see what happens when I fix this! 👍
