### ISSUE TITLE
Question on speed limit

### ISSUE THREAD

**Issue by alecava58** [itinero/routing#129]
I'd would like to know if a speed limit for vehicle type is used by the library.
Source: http://wiki.openstreetmap.org/wiki/Key:maxspeed

![image](https://user-images.githubusercontent.com/1788993/30369230-042bb764-9874-11e7-84c3-d5bb92d31168.png)

**Comment by mhosman** [comment]
Same question here!! Thank you!! Great lib!

**Comment by mhosman** [comment]
Nobody?

**Comment by xivk** [comment]
Yes, it is, for car by default. You can configure your own profiles and define how this gets used. Check the brand new docs:

http://docs.itinero.tech/docs/itinero/basic-concepts/profiles/index.html

**Comment by xivk** [comment]
Oh sorry, **the hgv:maxspeed tag isn't used** by default, sorry, should had read the question better. The answer is still the same, you can add the tag to a profile of your own.
