### ISSUE TITLE
Turn by Turn a little funky

### ISSUE THREAD

**Issue by rogerthoang** [itinero/routing#13]
I am not sure if this is normal, but here is a sample route turn by turn from Staples Center, Los Angeles,CA to Jeff's Gourmet Sausage , Los Angeles, CA.

[start] Start SouthEast.
[turn] Turn Right on Figueroa Street.
[turn] Turn SharpRight on West 12th Street.
[turn] Turn Left on West 12th Street.
[turn] Turn SharpRight on South Hope Street.
[turn] Turn TurnBack on South Hope Street.
[turn] Turn Right on South Hope Street.
[turn] Turn Left on Venice Boulevard.
[turn] Turn Left on South Grand Avenue.
[turn] Turn SharpRight on West 17th Street.
[turn] Turn TurnBack.
[turn] Turn TurnBack.
[turn] Turn TurnBack on Santa Monica Freeway.
[turn] Turn TurnBack on Santa Monica Freeway.
[turn] Turn TurnBack on Santa Monica Freeway.
[turn] Turn TurnBack on Santa Monica Freeway.
[turn] Turn TurnBack on Santa Monica Freeway.
[turn] Turn TurnBack on Santa Monica Freeway.
[turn] Turn TurnBack on Santa Monica Freeway.
[turn] Turn TurnBack on Santa Monica Freeway.
[turn] Turn TurnBack on Santa Monica Freeway.
[turn] Turn TurnBack on Santa Monica Freeway.
[turn] Turn TurnBack on Santa Monica Freeway.
[turn] Turn TurnBack on Santa Monica Freeway.
[turn] Turn TurnBack on Santa Monica Freeway.
[turn] Turn TurnBack on Santa Monica Freeway.
[turn] Turn TurnBack.
[turn] Turn TurnBack.
[turn] Turn TurnBack on Cadillac Avenue.
[turn] Turn TurnBack on Cadillac Avenue.
[turn] Turn TurnBack on Cadillac Avenue.
[turn] Turn TurnBack on Cadillac Avenue.
[turn] Turn TurnBack on Cadillac Avenue.
[turn] Turn TurnBack on Cadillac Avenue.
[turn] Turn TurnBack on Cadillac Avenue.
[turn] Turn TurnBack on Cadillac Avenue.
[turn] Turn TurnBack on Cadillac Avenue.
[turn] Turn TurnBack on Cadillac Avenue.
[turn] Turn TurnBack on Cadillac Avenue.
[turn] Turn TurnBack on Cadillac Avenue.
[turn] Turn TurnBack on Cadillac Avenue.
[turn] Turn TurnBack on Cadillac Avenue.
[turn] Turn TurnBack on Cadillac Avenue.
[turn] Turn TurnBack on Cadillac Avenue.                <-- TurnBack really mean StraightOn?
[turn] Turn Left on Cadillac Avenue.                         <-- this seems wrong
[turn] Turn TurnBack on Robertson Boulevard.
[turn] Turn TurnBack on Robertson Boulevard.
[turn] Turn TurnBack on Robertson Boulevard.
[turn] Turn TurnBack on Robertson Boulevard.
[turn] Turn SharpLeft on Robertson Boulevard.
[turn] Turn TurnBack on Robertson Boulevard.
[turn] Turn SharpRight on Robertson Boulevard.
[turn] Turn SharpRight on Robertson Boulevard.
[turn] Turn TurnBack on Robertson Boulevard.
[turn] Turn TurnBack on Robertson Boulevard.
[turn] Turn TurnBack on Robertson Boulevard.
[turn] Turn TurnBack on Robertson Boulevard.
[turn] Turn Right on Robertson Boulevard.
[turn] Turn TurnBack on Pico Boulevard.
[turn] Turn Left on Pico Boulevard.
[stop] Arrived at destination.
Total Travel Distance is: 14387.65
Total Travel Time is: 613.2098

**Comment by xivk** [comment]
Agreed, this part of the project could definetly be a lot better, the 'instructions' you are seeing here are the default bare-minimum. Usually custom instructions are built for custom vehicles, meaning the default is not very good.

I could get you started on how to improve this or you can wait until I find time to improve on this.

**Comment by rogerthoang** [comment]
Sure, I'd love to. Any tips and pointing on getting started?

**Comment by xivk** [comment]
The basics of the instruction generation is here:

https://github.com/itinero/routing/blob/develop/src/Itinero/Navigation/InstructionGenerator.cs

This takes an array of functions that generate instructions. Lower in the array, has a higher priority. Once a function generates an instruction it keeps the instruction locally.

An example implementation is probably the one you are using:

https://github.com/itinero/routing/blob/develop/src/Itinero/Navigation/Osm/InstructionCarGenerator.cs

If you email me ben@itinero.tech i can also help you using skype/hangout or maybe I should setup a slack channel.

**Comment by xivk** [comment]
Should be a **lot** better now and is now configurable in the profiles. Closing.
