### ISSUE TITLE
Question: ShortcutsDb

### ISSUE THREAD

**Issue by alecava58** [itinero/routing#130]
When you have time could you give me a brief description of the use case about ShortcutsDb.
Thanks.

**Comment by xivk** [comment]
This enables a simple form of static multimodal routing. For example this is a routeplanner for a bike-sharing system:

http://velo.anyways.eu/?fLat=51.224&fLon=4.3823&tLat=51.2098&tLon=4.4339

The routes between the bike stations are always the same, we call them the 'shortcuts' and we precalculate them all. We add them as edges in the RouterDb and the details and shapes of the edges along with the mode of transport, in this case 'bicycle' is in the ShortcutsDb.

This enables Itinero to combine these two modes and contract a graph to route pedestrians along a combination of bike sharing and walking.
