### ISSUE TITLE
Question - max weight for a vehicle

### ISSUE THREAD

**Issue by sulmar** [itinero/routing#131]
Can I add a weight limit for a vehicle in the lua script? For example maxweight < 3.5 t
I will be grateful for the hint.

**Comment by xivk** [comment]
Hmm, I think you can do that in the lua scripts, here is an example of an extra function to parse a speed:

https://github.com/itinero/routing/blob/develop/src/Itinero/Osm/Vehicles/car.lua#L165

It refers to this function:

https://github.com/itinero/routing/blob/develop/src/Itinero/Profiles/Lua/ItineroLib/ItineroModule.cs#L57

There is also parse weight:

https://github.com/itinero/routing/blob/develop/src/Itinero/Profiles/Lua/ItineroLib/ItineroModule.cs#L31

That should enable you to get the weight as a number in **kilograms** even if another unit is given.

**Comment by sulmar** [comment]
Something like this?
```
if attributes.maxweight then
		local weight = itinero.parseweight(attributes.maxweight)
		if weight < 3.5 then
			result.speed = 0
			result.direction = 0
			result.attributes_to_keep.maxspeed = true
		end
	end
```

**Comment by xivk** [comment]
Yes, that should work, small change:

```
       if attributes.maxweight then
		local weight = itinero.parseweight(attributes.maxweight)
		if weight < 3.5 then
			result.speed = 0
			result.direction = 0
			result.attributes_to_keep.maxweight = true -- keep maxweight
		end
	end
```

**Comment by xivk** [comment]
Oh, sorry no like this:

```
       if attributes.maxweight then
		local weight = itinero.parseweight(attributes.maxweight)
		if weight < 3500 then -- weight is always returned in kg.
			result.speed = 0
			result.direction = 0
			result.attributes_to_keep.maxweight = true -- keep maxweight
		end
	end
```

**Comment by sulmar** [comment]
Thank you very much.

I have then the code:
```

var vehicle = new DynamicVehicle(LoadEmbeddedResource("truck3500.lua"));


                var routerDb = new RouterDb();

                // load the raw osm data.
                var routerDbFile = Path.Combine(baseDir, RouterDbFile);

                if (!File.Exists(routerDbFile))
                {
                    using (var stream = new FileInfo(Path.Combine(baseDir, Download.PolandLocal)).OpenRead())
                    {
                        routerDb.LoadOsmData(stream, vehicle);
                    }

                    using (var stream = new FileInfo(Path.Combine(baseDir, RouterDbFile)).OpenWrite())
                    {
                        routerDb.Serialize(stream);
                    }
                }
                else
                {
                    routerDb = RouterDb.Deserialize(File.OpenRead(routerDbFile));
                }
```

Is it well done?

**Comment by xivk** [comment]
Yes I think so, you could also contract a version of the graph to have faster routing. I just realized there isn't anything about contraction in the docs. Adding a TODO here to add that:

- [ ] Add info about contraction to the docs.

**Comment by sulmar** [comment]
Somethink like this?

  ```
RouterDb routerDb = RouterDbBuilder.Build(baseDir);

            var vehicle = routerDb.GetSupportedVehicle("mytruck");

            var router = new Router(routerDb);

            var profile = vehicle.Shortest();

            routerDb.AddContracted(profile);

            var route = router.CalculateTSP(profile, locations, 0, locations.Count() - 1);
```

**Comment by xivk** [comment]
Yes, contract the exact same profile as the one you are using. Also, save the routerdb after contraction so you only need to contract once:


```

var vehicle = new DynamicVehicle(LoadEmbeddedResource("truck3500.lua"));


                var routerDb = new RouterDb();

                // load the raw osm data.
                var routerDbFile = Path.Combine(baseDir, RouterDbFile);

                if (!File.Exists(routerDbFile))
                {
                    using (var stream = new FileInfo(Path.Combine(baseDir, Download.PolandLocal)).OpenRead())
                    {
                        routerDb.LoadOsmData(stream, vehicle);
                    }
                    
                    // do contraction here.
                    routerDb.AddContract(vehicle.Shortest());

                    using (var stream = new FileInfo(Path.Combine(baseDir, RouterDbFile)).OpenWrite())
                    {
                        routerDb.Serialize(stream);
                    }
                }
                else
                {
                    routerDb = RouterDb.Deserialize(File.OpenRead(routerDbFile));
                }
```

**Comment by alecava58** [comment]
I think should be less or equal.
More if you put this code before the parsespeed you have to add a return after the first end.
  
     if attributes.maxweight then
		local weight = itinero.parseweight(attributes.maxweight)
		if weight <= 3500 then -- weight is always returned in kg.
			result.speed = 0
			result.direction = 0
			result.attributes_to_keep.maxweight = true -- keep maxweight
		end
                return
	end

**Comment by xivk** [comment]
Closing this, added information about contraction to the docs:

https://github.com/itinero/docs/commit/7eae4be2795e3866fe6637293511d72c38f64904

**Comment by slemvs** [comment]
Hi @xivk, thank you for great and very usefull library. 
In case above, can we set weight of the vehicle in runtime (not hardcoded constant in lua "3500", but any variable that we could check)? 
Is there any "constraints" of the vehicle from C# code available in lua?

In my application user can add to own profile several vehicles, for example, several small trucks with different heights: 3m and 4m. Can we use for this case one lua profile, save contracted db with this lua profile and use it later with 2 different vehicles with different heights?
