### ISSUE TITLE
Invalid Source and target in calculate WeightMatrixAlgorithm

### ISSUE THREAD

**Issue by boaniben** [itinero/routing#132]
Hi, 
I want to calculate weight matrix for big amount of points.
I even call resolve before the calaute weigth matrix but it still return invalid source and target.
Here is an small example of 2 points which i try to calculte the weight matrix:

var router = new Router(routerDb);
var locations = new Coordinate[2]
{
    new Coordinate((float)32.0836639, (float)34.78513),
    new Coordinate((float)32.07799, (float)34.78133)

};
var matrixCalculator = new Itinero.Algorithms.Matrices.WeightMatrixAlgorithm(
 router, Vehicle.Car.Fastest(), locations);
matrixCalculator.Run();

What do you think is the best way to get weight matrix for big amount of point.
I need to find the weight from each point to others.

Thanks!

**Comment by boaniben** [comment]
Hi,
I also tried to change the profile of the DB to shortest instead of fastest, and now it don't return invalid resources or targets but now the wieght matrix have filled out with max value for some pints (please see the attached image).
Can you please help me to understand why their is max value in the wieght and what is the best way to get full weight matrix from all points to the all other points?

I really appreaciate your help.
I have to say that you did a great job with itinero!!

![weight matrix](https://user-images.githubusercontent.com/32322759/30953681-9ebc7b3e-a435-11e7-8bb1-d4694f30bfe0.png)

Thanks!

**Comment by xivk** [comment]
In some rare cases there are routing islands. Did you try calculating a route between the two invalid locations to see what happens?

**Comment by xivk** [comment]
Check the example here on how to do this:

http://docs.itinero.tech/docs/itinero/basic-concepts/index.html#example

**Comment by boaniben** [comment]
Hi,
Yes i tried calculating a route for the invalid locations and the calculated route works fine - it returned distance and duration.
The issue is that the WeightMatrixAlgorithm returned errors for all the locations in the location array.
I think the problem is in the RouterDB which i serialized. I don't know why but the supported profile in the RouterDB are only car, car.shortest, and car.clasifications. Somehow the car.fastest doesn't appear although i created contracted DB with Car.Fastest profile.

![image](https://user-images.githubusercontent.com/32322759/31015246-cb3b1470-a527-11e7-8812-4d15967d6bfb.png)



**here is how we LoadOsmData, AddContracted and Serialize the RouteDB:**
if (RouterDb == null)
            {

                using (var stream = System.IO.File.OpenRead(@"C:\Delivery\Delivery 4.0\itinero\routing-api\src\Itinero.API\datashortest2\israel-and-palestine-latest.osm.pbf"))
                {
                    RouterDb = new RouterDb();
                    RouterDb.LoadOsmData(stream, Itinero.Osm.Vehicles.Vehicle.Car);
                }

                using (var stream = System.IO.File.Open(@"C:\Delivery\Delivery 4.0\itinero\routing-api\src\Itinero.API\datashortest2\israel.routerdb", System.IO.FileMode.Create))
                {
                    RouterDb.Serialize(stream);
                }

            }

            if (RouterDb != null)
            {
                if (!RouterDb.HasContractedFor(Itinero.Osm.Vehicles.Vehicle.Car.Shortest()))
                {
                    //Itinero.Logging.Logger.Log("RouterDbBuilder", Itinero.Logging.TraceEventType.Information, "No contracted graph found for the 'car' profile, building now...");
                    RouterDb.AddContracted(Itinero.Osm.Vehicles.Vehicle.Car.Shortest());

                    using (var stream = System.IO.File.Open(@"C:\Delivery\Delivery 4.0\itinero\routing-api\src\Itinero.API\datashortest2\israel.routerdb", System.IO.FileMode.Create))
                    {
                        RouterDb.Serialize(stream);
                    }
                }
            }


I also tried to run the WeightMatrixAlgorithm on new contracted DB with Car.Shortest profile and still i get errors like ""Location could not routed to or from."

Here more coordinates which i get errros in both fastest and shortest profiles:
var locations2 = new Coordinate[7]
            {
                new Coordinate((float)31.77018, (float)34.6401176),
                new Coordinate((float)31.7796612, (float)34.6322479),
                new Coordinate((float)31.7867336, (float)34.6359177),
                new Coordinate((float)31.7820415, (float)34.64277),
                new Coordinate((float)31.7896976, (float)34.63987),
                new Coordinate((float)31.7861328, (float)34.6270943),
                new Coordinate((float)31.79527, (float)34.6402359)
            };
            var matrixCalculator = new Itinero.Algorithms.Matrices.WeightMatrixAlgorithm(
            router, Itinero.Osm.Vehicles.Vehicle.Car.Shortest(), locations2);
            matrixCalculator.Run();


            var profile = Itinero.Osm.Vehicles.Vehicle.Car.Shortest();
            var start = router.Resolve(profile, 32.0836639f, 34.78513f);
            var end = router.Resolve(profile, 32.07799f, 34.78133f);
            var route_start_to_end = router.Calculate(profile, start, end);
            var route_end_to_start = router.Calculate(profile, end, start);

**Comment by xivk** [comment]
Can you verify this is still an issue? I tried these calculations with the latest prerelease and I don't have any problems there, all routes succeed nicely both point to point and in the weight matrix calculations.

**Comment by xivk** [comment]
Closing this, assumed fixed in latest prerelease.
