### ISSUE TITLE
Implement a point in polygon algorithm.

### ISSUE THREAD

**Issue by xivk** [itinero/routing#138]
We need an implementation for a point in polygon algorithm, more info can be found [here](http://docs.itinero.tech/docs/itinero/development/features/2017-11-15-point-in-polygon.html).

If you are a new contributor this is perfect, get in touch by responding below. Your code will end up in our next release after finishing. What we think you can learn:

- More about geo-algorithms.
- More about routing/itinero.
- Maybe some C#.
- How to contribute to open-source projects.

What you need:

- A computer with Linux, Windows or MacOS.

We'll help you get started and we can offer personal guidance.

**Comment by airbreather** [comment]
https://github.com/NetTopologySuite/NetTopologySuite/blob/2c0f950c7deb77ab780b28396cb11d63dc250a1d/NetTopologySuite/Algorithm/Locate/IndexedPointInAreaLocator.cs

^ fastest I'm aware of, requires some preprocessing on the polygon

https://github.com/NetTopologySuite/NetTopologySuite/blob/2c0f950c7deb77ab780b28396cb11d63dc250a1d/NetTopologySuite/Algorithm/PointLocator.cs

^ fastest I'm aware of that doesn't require any preprocessing

**Comment by xivk** [comment]
Work is ongoing now here:

https://github.com/pietervdvn/routing

An open question:

- [ ] For performance reasons it could be useful to cache the boundingbox on the polygon. We need to investigate some more and decide on a strategy.

**Comment by xivk** [comment]
Thanks @pietervdvn 👍
