### ISSUE TITLE
Very optimistic time distance calculation in cities

### ISSUE THREAD

**Issue by maarno** [itinero/routing#140]
Hi,

we're using Itinero 1.3 to calculate the distance and time mostly within cities.
Unfortunately the results we get for the driving time are not very realistic.
I checked it with several examples and they all came out being too optimistic.

Example:
Profile: Vehicle.Car.Fastest()
1.3045, 103.8926 -> 1.3069, 103.8277

Itinero: 10km distance, 11:13min driving time
Google: 10.7km distance, 20:00min driving time
OSM (Car OSRM): 11km, 19:00min driving time

As you can see the Itinero calculates a very optimistic (and not very realistic) driving time.
I played around with the LUA profiles and changed the speed profiles but it doesn't have a big impact and goes nowhere close to the realistic 20 minutes.

https://www.openstreetmap.org/directions?engine=osrm_car&route=1.3045%2C103.8926%3B1.3069%2C103.8277#map=14/1.2998/103.8835

![image](https://user-images.githubusercontent.com/16541417/33255986-f89e3154-d38a-11e7-9256-18030a679157.png)

I verified this with multiple other examples and most of them ended up with about 1 minute driving time for 1km.
Another example would be:
e.g. 1.320926, 103.780159 -> 1.308428, 103.892836
Itinero: 15.9km, 14:23min
OSM (Car OSRM): 17km, 24:00min
Google: 17.7km, 22min

The code I'm using to calculate is as follows:

```
            AlgoMap map = AlgoMap.SingaporeMalaysiaBrunei;

            var vehicleProfile = Vehicle.Car.Fastest();
            var routers = new ConcurrentDictionary<AlgoMap, Router>();

            using (var stream = new FileInfo("malaysia-singapore-brunei-latest.osm.routerdb").OpenRead())
            {
                var routerDb = RouterDb.Deserialize(stream);
                routers.TryAdd(map, new Router(routerDb));
            }

            var routerPointFrom = routers[map].TryResolve(vehicleProfile, new Coordinate((float)from.Latitude, (float)from.Longitude), 300);

            var routerPointTo = routers[map].TryResolve(vehicleProfile, new Coordinate((float)to.Latitude, (float)to.Longitude), 300);

            var route = routers[map].TryCalculate(vehicleProfile, routerPointFrom.Value, routerPointTo.Value);
            var drivingTime = TimeSpan.FromSeconds(route.Value.TotalTime);
```

Is there anything I'm doing wrongly? Is there a workaround? A more pessimistic lua profile?

Help with this matter would be very much appreciated.

Cheers
Martin

**Comment by xivk** [comment]
The only option here is a more pessimistic lua profile. Not sure what the other routing engines do, perhaps they are more pessimistic in urban areas or they know more then Itinero has access to like for example historical estimated travel times (google definitely uses this).

**Comment by maarno** [comment]
thank you for your answer.
I played around with more pessimistic lua profiles but then I end up getting unrealistic driving times for long haul routes.

I'm aware Google uses historical data and also live traffic data for the driving time, that's why I also compared their driving time with the time set to 3am in the morning.

Is improving the driving time something on the road map of Itinero?
If so, I'm sure you know the open source OSRM project? Their driving time is pretty realistic. It might be worth a closer look what they do.

**Comment by xivk** [comment]
From what I know OSRM is going to calculate travel times in a similar way as Itinero, classification-based and max-speed based estimates. Maybe they also take into account urban areas (and area-based maxspeeds), something that is probably going to appear on the Itinero roadmap too. 

I'll see if I can change some of the speed profiles to closer align with expectations.

We do a lot of projects with Itinero but usually users/companies build their own lua profiles for their own usecases. Thanks for the feedback in any case. Did you try and reduce the guestimates for the speeds to get them to align more with the others?

**Comment by xivk** [comment]
Closing this issue, there is better support for traffic info & urban areas on the [roadmap](http://docs.itinero.tech/docs/itinero/development/index.html). If there is any more feedback fee free to reopen.
