### ISSUE TITLE
Static readonly fields must be thread safe

### ISSUE THREAD

**Issue by Georgy-Losenkov** [itinero/routing#142]
Version=1.3.1.0
readonly field Itinero.Osm.Vehicles.Vehicle.Car contains (and uses) reference to Lua.Script which prevents it from using in multiple threads (for example async methods)

Workaround:
take Script or processor within it from the cache (similar to StringBuilderCache)

**Comment by xivk** [comment]
Can you give a bit more details about this or suggest a more detailed fix? Where does this go wrong exactly?

**Comment by xivk** [comment]
Closing this, no reply for 5 months. Feel free to reopen if this is still an issue.
