### ISSUE TITLE
Using Shapefile to create RouterDb

### ISSUE THREAD

**Issue by jerryfaust** [itinero/routing#144]
Hello.
Is there updated documentation or sample code on how to create a RouterDb from a Shapefile?  The interfaces apparently have changed since the current documentation was published (http://docs.itinero.tech/docs/itinero/data-sources/shapefiles.html), and for now I'm trying to figure it out by browsing the source code.
Thank you for any assistance.
Jerry.

**Comment by xivk** [comment]
The sample moved here and this is tested before every release:

https://github.com/itinero/geo/tree/master/samples/Sample.Shape

And the docs are out-of-date, I will update... thanks!

**Comment by xivk** [comment]
Docs are updated, updated sample readme, closing this issue feel free to reopen if you have any further issues with this.
