### ISSUE TITLE
Resoving endpoints on network built from Shapefile

### ISSUE THREAD

**Issue by jerryfaust** [itinero/routing#148]
Hello.

I'm trying to traverse a network built using a Shapefile, and having trouble resolving start and end points.  Stepping through, I've determined (to the best of my understanding) that the network is fine, the vertex/edge resolution is correct, but the point is always rejected in the GetIsAcceptable function (ProfileFactorAndSpeedCache.cs, line 140).  The cachedFactors array contains two elements, presumably associated with my Speed and Distance profiles, but they both appear to be set to NoFactor (all zeroes).

I'm guessing that it has something to do with my LUA vehicle profile; I've tried multiple variations on the minimal profile from the documentation.  Presuming that there's very little information available within the Shapefile itself, can I provide a basic profile as the following?

Thank you.

name = "car"
-- whitelists for profile and meta
profile_whitelist = {
    "sdsfeature" -- field from the street centerline shapefile
}
meta_whitelist = {
    "roadname"
}
-- profile definitions linking a function to a profile
profiles = {
    {
        name = "",
        function_name = "factor_and_speed",
        metric = "time"
    },
    { 
        name = "shortest",
        function_name = "factor_and_speed",
        metric = "distance",
    }
}
-- the main function turning attributes into a factor_and_speed and a tag whitelist
function factor_and_speed (attributes, result)

     result.speed = 50
     result.direction = 0
     result.canstop = true
     result.attributes_to_keep = attributes.sdsfeature

end

**Comment by xivk** [comment]
There are several 'debugging' options for a network, for example you could get a GeoJSON of an area by using routerDb. GetGeoJSONIn() or GetGeoJSONAround() and see what your network looks like.

I also think the factor_and_speed function isn't 100% correct, check the sample for the Dutch NWB network:

https://github.com/itinero/geo/blob/master/samples/Sample.Shape/car.lua#L61

Perhaps change this line:

```result.attributes_to_keep = attributes.sdsfeature```

to

```result.attributes_to_keep.sdsfeature = true```

My best guesses without starting to write code myself.

**Comment by jerryfaust** [comment]
[Routing Library Notes.docx](https://github.com/itinero/routing/files/1675489/Routing.Library.Notes.docx)

For your review, I have submitted some of my findings related to the generation and usage of a network based on a Shapefile.  Thank you.

**Comment by xivk** [comment]
I opened the doc, need a bit more time to review later 👍 
- [ ] Review notes above.

**Comment by xivk** [comment]
Closing this issue, opening a new one to improve turn-by-turn instructions.
