### ISSUE TITLE
Time in ShapeMeta collection is not progressive

### ISSUE THREAD

**Issue by alecava58** [itinero/routing#15]
I'm trying to calculate the interdistance between stops using the method below, and the distances seem to be progressive but the times don't (sometime I have negative values).
Did I make a mistake?

```
            // rebuild interdistances
            float ml = 0;
            float tl = 0;
            IList<IInterdistance> inter = new List<IInterdistance>();
            foreach (var stop in route.Stops)
            {
                var m = route.ShapeMeta.First(s => s.Shape == stop.Shape).Distance / 1000;
                var t = route.ShapeMeta.First(s => s.Shape == stop.Shape).Time / 60;
                inter.Add(new Interdistance { Distance = m - ml, Time= t - tl });
                ml = m;
                tl = t;
            }
```

**Comment by xivk** [comment]
@alecava58 Have an example route?

**Comment by alecava58** [comment]
I'm not able to reproduce the problem using Luxemburg map. But now I'm using the new Time property of Stops so everithing seems to be ok.
I think you can close the problem unless someone can reproduce it.
