### ISSUE TITLE
Support cancelation tokens

### ISSUE THREAD

**Issue by goersen** [itinero/routing#156]
Suggestion
-

Itinero superbly supports multithreaded route-calculations out of the box.
It would be very nice if cancelation tokens were supported as an option when calculating a route in a background-thread.

Use Case
-

When running Itinero RouterDb with a limited-cache-option (i.e. on a mobile device) calculating a route can take quite some time. This would usually be done in a background-thread as to not bother the user with having to wait. Further user-interaction can make the calculation obsolete (i.e. the user changed the route in some way, navigated to another screen, ...). In this case it would be nice to be able to stop the calculation on the background thread.

Suggested Code addition
-

From what I understand this could be achieved relatively easily by adding an optional cancelation token to the calculate APIs and check the cancelation token either in
`RouterBaseExtensions` --> `Result<Route> TryCalculate(this RouterBase router, IProfileInstance profile, RouterPoint source, RouterPoint target)`
or
`Router` --> `Result<EdgePath<T>> TryCalculateRaw<T>(IProfileInstance profileInstance, WeightHandler<T> weightHandler, RouterPoint source, RouterPoint target,
            RoutingSettings<T> settings) `

**Comment by goersen** [comment]
Would you agree with this suggestion or do you think there is a better approach to handle this?

**Comment by xivk** [comment]
This is a good suggestion! How do other libraries handle this? Any ideas?

There is already support in most of the calculations to cancel the run but it's not exposed yet. In some cases this needs some work but shouldn't be that hard to implement.

**Comment by goersen** [comment]
API-wise I would personally say it's a matter of personal preference and time-investment. I see three naive ways which I'm used to as a library-consumer:

#### 1. Quick and Easy
- Just add APIs which accept cancelation tokens
- Tokens are regularly checked during calculation and interupted when the token is canceled
- Results are returned synchronously and mostly unchanged
- Threading is handled completely by the library-consumer

##### Example Usage
```
class MyClass 
{
    Router router;
    Route resultRoute;
    CancelationTokenSource cancelationTokenSource;

    void CalculateIWithtineroInBackground(IProfileInstance profile, RouterPoint[] points)
    {
        cancelationTokenSource = new CancelationTokenSource();
        Task.Factory.StartNew(new Action(() =>
        {
            resultRoute = router.Calculate(profile, points, cancelationTokenSource.Token);
        }));
    }

    void OnSomethingHappens()
    {
        cancelationTokenSource.Cancel();
    }
}
```

&nbsp;

#### 2. Basic background-calculation API
- Add APIs like `TryCalculateInBackground(profile, points, onFinishedCallback, cancelationToken, ...)`
- The API accepts cancelation-tokens and calculation stops on cancel
- Threading is handeled inside Itinero
- Results are returned to a delegate-function which is given to `TryCalculateInBackground`

##### Example Usage
```
class MyClass 
{
    Router router;
    Route resultRoute;
    CancelationTokenSource cancelationTokenSource;

    void CalculateIWithtineroInBackground(IProfileInstance profile, RouterPoint[] points)
    {
        cancelationTokenSource = new CancelationTokenSource();
        router.CalculateInBackground(profile, points, OnCalculationFinished, cancelationTokenSource.Token);
    }

    void OnCalculationFinished(Route route)
    {
        resultRoute = route;
    }

    void OnSomethingHappens()
    {
        cancelationTokenSource.Cancel();
    }
}
```

&nbsp;

#### 3. Add a full-fledged Background-Calculation wrapper
- Implement a wrapper-class which represents the calculation
- The wrapper contains the calculation-status, -result, different events for completed, success, error, etc. (or just "OnStatusChanged") as well as a function to stop
- Threading is handeled inside itinero
- Calculation-result can be accessed in a variable and is maybe handed in a success-event
- This could also be used in the future to implement a progress-update (i.e. 'calculation 52% completed')

##### Example Usage (obviously there are a million different ways to expose such an API)
```
class MyClass 
{
    Router router;
    Route resultRoute;
    ItineroBackgroundCalculation backgroundCalculation;

    void CalculateIWithtineroInBackground(IProfileInstance profile, RouterPoint[] points)
    {
        backgroundCalculation = router.GetBackgroundCalculation(profile, points);
        backgroundCalculation.OnFinished += OnCalculationFinished;
        backgroundCalculation.OnError += OnCalculationError;
        backgroundCalculation.OnProgressChanged += OnCalculation
        backgroundCalculation.Run();
    }

    void OnCalculationFinished(Route route)
    {
        resultRoute = backgroundCalculation.Result;
    }

    void OnCalculationError(Error error)
    {
        System.Diagnostics.Debug.WriteLine( " :-( " );
    }

    void OnCalculationProgressChanged(int newProgress)
    {
        UpdateMyProgressBar(newProgress);
    }

    void OnSomethingHappens()
    {
        backgroundCalculation.Stop();
    }
}
```

**Comment by airbreather** [comment]
Suggestion 3 roughly follows what's called the [Event-based Asynchronous Pattern (EAP)](https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/event-based-asynchronous-pattern-eap) and is no longer recommended for new development.  The recommended approach these days is called the [Task-based Asynchronous Pattern (TAP)](https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap), which also prescribes a different mechanism for progress reporting.

If Itinero won't be doing anything meaningfully smarter than just `Task.Run` to do stuff in the background, then my recommendation is to add and use `CancellationToken` and `IProgress<T>` parameters where it makes sense, but leave it up to the callers to decide how and when to call it from a background thread.  They can always just call `Task.Run` themselves, but sometimes a caller has a specific thread that they would want to run this stuff on, so this gives them options.

**Comment by goersen** [comment]
@airbreather: Thanks for the quick educational references! :)
Also sorry for giving outdated suggestions :(. 

I also agree that letting the consumers handle the threading is more flexible for them. `IProgess<T>` would be a great addition for this!

**Comment by xivk** [comment]
OK, thanks! Let's go with @airbreather's suggestions. I'll try to write-up what needs to be done with all the details and put it on the roadmap.

Then depending on my own time or someone picking this up it will be done as planned! 👍

**Comment by JoeCooper** [comment]
I've done this before, to my own fork, back before the name was changed to Itinero. I could do it again, but it does change the API. Perhaps I could do it again. @xivk Do you have any guidelines about API changes?

**Comment by xivk** [comment]
We could co-author a small draft outlining the design together? It cannot be a breaking change otherwise we have to wait until work is started on 2.0. For reference, here is the roadmap:

http://docs.itinero.tech/docs/itinero/development/index.html

**Comment by xivk** [comment]
I'm have been close to releasing 1.4 for weeks now (ouch) so yes, this would be for 1.5... and euh 'ABI' what do you mean by that?

In any case I think it's possible to add this in a way that doesn't break things looking at option 1 above.

**Comment by JoeCooper** [comment]
Yah so if for example you add a cancellation token as a parameter on to the end of an extant method's parameter list and give it a default parameter, current code will still compile against it unmodified.

But current _builds_ won't be able to resolve the method they're linked to, because it has been replaced with a different method that has a different set of parameters. The _binary interface_ (the BI in ABI) is different.

But I don't know if this matters because I don't know what everyone else is doing.

I've been working with mobiles and with ASP.NET and in both cases the above wouldn't matter because you never deploy without also recompiling. But (for example) if it were installed as a shared library, applications depending on it would fail.

So (if it matters) the solution is not to use a default parameter to maintain compatibility, but instead to have a wrapper method which matches the current spec. But if it doesn't matter, default parameters are nicer.

Since you're interacting with other users and customers you know better than I do what matters. What say you?

**Comment by xivk** [comment]
I think this is acceptable but wouldn't adding an overload instead of a default parameter fix this issue?

**Comment by JoeCooper** [comment]
Yes, overload is what I mean. Sorry I forgot the word for it. The choice is default parameter or overload. I don’t know if it matters or not so I’m just asking.

**Comment by xivk** [comment]
Ah ok, a mixup in terminology then... this is quite a bit of work but if you're willing to implement this I'm more than happy that you do this. Can we first either make a draft on what the implementation is going to look like? Or meet on gitter/slack and discuss before is also ok.

I just want to avoid you doing the work and end up with a hanging pull-request 👍

**Comment by JoeCooper** [comment]
Sure, that makes sense. I’ve got to take care of some bugs but I’m going to come back to this later this week if something doesn’t come up.

**Comment by xivk** [comment]
Ok, perfect, thanks!

**Comment by JoeCooper** [comment]
(Sorry for the delay here. I'm checking with my client before I do this.)

**Comment by JoeCooper** [comment]
Have you ran into something like this:

![screen shot 2018-03-27 at 11 28 17 am](https://user-images.githubusercontent.com/5166338/37958910-0cb47bb4-31b2-11e8-8e6a-88b6cf0ce3ae.png)

**Comment by JoeCooper** [comment]
> Can we first either make a draft on what the implementation is going to look like?

As far as I can tell, I need to edit these interfaces: 
https://mazuku-staging.herokuapp.com/documents/zrzZB6alCSqLBWP2cZ8G_w

Am I forgetting any?

Internally, we only need to add the interface to sub sections which consume a large chunk of the time, and put checks to throw on cancellation at key points.

> Or meet on gitter/slack and discuss before is also ok.

Let me know where you want to be contacted, or if you want to let me into a slack channel.

**Comment by JoeCooper** [comment]
I'm going into it. I see there's a lot of interfaces in router base extensions. There will be separate commits and I'll present you with updates at particular stages.

**Comment by JoeCooper** [comment]
Please examine this PR: https://github.com/itinero/routing/pull/176

@goersen Are you still interested in this issue?

**Comment by xivk** [comment]
This is now done! Thanks y'all!
