### ISSUE TITLE
Question: Enumerate edges and vertexes

### ISSUE THREAD

**Issue by alecava58** [itinero/routing#158]
Having a routerDB may I enumerate all edges and vertexes along with their meta and attributes?

Thanks

**Comment by xivk** [comment]
Perfectly possible but watch out when modifying the data while enumerating. An example is here: $

https://github.com/itinero/routing/blob/develop/src/Itinero/Algorithms/Networks/ZeroLengthLinksOptimizer.cs#L50

This code removes links of length '0'

**Comment by alecava58** [comment]
Ok. thanks for the tips.
