### ISSUE TITLE
Question: best option to handle temporary closure

### ISSUE THREAD

**Issue by alecava58** [itinero/routing#159]
What is the best option to handle temporary closure of a street?

This should be handle without rebuilding the router db.

Thanks

**Comment by xivk** [comment]
At the moment this is not supported but you could adapt the current code to do something similar or wait for the feature that makes it possible to edit edge meta-data.

**Comment by alecava58** [comment]
Ok. Thanks Ben.
I'll take a look at the code trying to find out the right place to handle this option.

I simply tried to remove an edge with no luck.

**Comment by xivk** [comment]
This is directly related to #146 and that's in progress so closing (but @alecava58, removing an edge should work but you have to rebuild the contracted graph after **every** change)
