### ISSUE TITLE
Total Distance Always 0

### ISSUE THREAD

**Issue by kevin-work** [itinero/routing#16]
I've read the Wiki and tried all sorts of ways to calculate distance and the only overload which has worked on the ```TryCalculate``` was where the actual float lat and long values were passed in. Using ```RouterPoint``` and ```Coordinate``` ends up with 0 distance.

    var routerDb = new RouterDb();
    using (var stream = new FileInfo(OsmFileName).OpenRead())
    {
        routerDb.LoadOsmData(stream, Vehicle.Car);
    }
    var router = new Router(routerDb);

    const int numberOfRoutes = 10;
    var calculatedRoutes = new List<RouterPoint>();
    var matrix = new float[numberOfRoutes, numberOfRoutes];
    var profile = Vehicle.Car.Fastest();

    for (var i = 0; i < numberOfRoutes; i++)
    {
        var fromRouterPoint = router.TryResolve(profile, /*lat*/, /*long*/);
        if (fromRouterPoint.IsError)
        {
            Console.WriteLine($"Failed to resolve point: {fromRouterPoint.ErrorMessage}");
            continue;
        }

        for (var j = 0; j < calculatedRoutes.Count; j++)
        {
            var route = router.TryCalculate(profile, fromRouterPoint.Value, calculatedJobs[j]);

            if (route.IsError)
            {
                Console.WriteLine($"Failed to calculate route: {route.ErrorMessage}");                        
            }
            else
            {
                matrix[i, j] = route.Value.TotalDistance;
                matrix[j, i] = route.Value.TotalDistance;
                calculatedRoutes.Add(fromRouterPoint.Value);
            }
        }
    }

In the matrix that I get back, all values are 0. Am I missing something?

**Comment by xivk** [comment]
I would recommend not calculating a weight matrix like this. Usually you use a contracted version of the network to calculate a matrix of times/distances. I added a sample that shows how to calculate weight matrices:

https://github.com/itinero/routing/tree/develop/samples/Sample.Matrix

Leaving this issue open to check why the distance is 0 in this case, is definetly a bug. Thanks for taking the effort to report this!

**Comment by xivk** [comment]
@kevin-work Thinking about closing this issue. Did you manage to find a solution?

I checked the distance calculation and it looks find, not sure what is happening... area and lat/lons of the routes being calculate would allow me to test further.

**Comment by kevin-work** [comment]
@xivk Seems to be working fine. I'm not sure why I had the original problem to begin with. Sorry for your time.
