### ISSUE TITLE
Is it possible to serialize a Itinero.Profiles.Profile?

### ISSUE THREAD

**Issue by pingurus** [itinero/routing#160]
I'd like to serialize an Itinero.Profiles.Profile, but this seems not to be possible. Is there any simple way to do this, or do I have to code some workaround for my project?

**Comment by xivk** [comment]
You can serialize a vehicle only if it's a lua profile (and then it's just a string with the original lua-code), otherwise you have to include and build your vehicle code into whatever app is loading the routerdb.

**Comment by pingurus** [comment]
Thanks!
