### ISSUE TITLE
RouterDb Contraction question.

### ISSUE THREAD

**Issue by pingurus** [itinero/routing#167]
Hi, 
I'm trying to add contracted routing Data to a RouterDb this way:
`var routerDb = new RouterDb();`
`using (var stream = new FileInfo(@"/path/to/some/osmfile.osm.pbf").OpenRead())`
`{`
   ` // create the network for cars only.`
    `routerDb.LoadOsmData(stream, Vehicle.Car); `
`}`
`routerDb.AddContracted(routerDb.GetSupportedProfile("car"));`

This however is causing a SystemOutOfMemory Exception when the used RAM hits 2GB. The .osm.pbf file is only 400MB. Am I doing something wrong, or should I use smaller osm.pbf files?

**Comment by xivk** [comment]
This should work, what version of Itinero are you using? 

Are you on windows/.NET framwork, make sure you build as x64.

**Comment by pingurus** [comment]
How much time do you expect it to take? Importing finished in 20min, Contracting is running since 1h. It currently uses 2.6GB RAM, so switching off the 32Bit option in VS prevented the SystemOutOfMemory Exception.
I'm using Itinero 1.3.2.0 from NuGet

**Comment by pingurus** [comment]
I aborted it after 2h.

**Comment by xivk** [comment]
Try the prerelease, that should be a lot better.

**Comment by goersen** [comment]
@pingurus 
For us it also only worked with the pre-release and with a x64  build. But depending on your data it might still take a long time.
We use osm-data of germany and that took 4-6 hours and 8-10 GB RAM (but page-files work here).
So just be patient and maybe let it run over night. You only need to do it once.

**Comment by pingurus** [comment]
How much is the performance gain after contraction?

**Comment by goersen** [comment]
@pingurus
Very significantly. For a route with ~8 points it was something like 30sec => 2-3sec.

**Comment by pingurus** [comment]
Thank you!

**Comment by xivk** [comment]
On top of that I think what @goersen is describing is the result of what the optimization library does if I'm not mistaken. For the optimization of a route with 8 locations first a matrix of 8x8 weights is calculated (or possibly 16x16) and then afterwards 7 or 8 routes depending on what's requested.

If you are still having performance issues @pingurus let us know in this issue, it's one of the most important features of this library, routing performance.

**Comment by xivk** [comment]
Closing this, feel free to reopen if there are any other questions.
