### ISSUE TITLE
question: adding custom info to routerdb

### ISSUE THREAD

**Issue by alecava58** [itinero/routing#168]
Hi Ben,

I'd like to know if I can add, and later extract, some custom info during a creating router db process (a simple string could be enough) to router db itself.
for example adding a string like this:
"OSM updated since 08/03/2018; builder vers: 1.3.14"

Thanks

**Comment by xivk** [comment]
There is a Meta property on the routerdb, you can add any key-value pair to that and it should be saved with the db.

**Comment by alecava58** [comment]
Very good.
Thanks.
