### ISSUE TITLE
Add support for starting or ending a route in a given direction

### ISSUE THREAD

**Issue by xivk** [itinero/routing#171]
Add support for starting or ending a route in a given direction. This should be based on an angle in degrees relative to the meridians.

It's already possible to do this kind of routing but a workaround is needed to calculate the angle of the current edge vs the requested angle. We want this built into the Itinero API.

**Comment by JoeCooper** [comment]
I've done this before (in an OsmSharp fork), and my client wants this feature, because they want the want the routing to take into account the driver's current direction.

Is this something you're already working on? Do you have a plan for the API? Is there a way I can participate?

**Comment by JoeCooper** [comment]
Is this "features/directed-routerpoints"?

**Comment by xivk** [comment]
This is pretty much done, that branch was merged already:

https://github.com/itinero/routing/commit/aaa4e6a76de0f64736109093dff54df5aeeb86e2

I was planning on updating the functional tests to reflect this new feature and add some documentation:

- [ ] Add documentation for this.
- [ ] Update functional tests.

**Comment by JoeCooper** [comment]
If I'm reading this correctly, your solution is substantially smarter than the one I came up with. I'm gonna try this out.

**Comment by xivk** [comment]
If you find anything that doesn't look right, let me know. I will be using this myself soon but haven't up until now. Also the API could be made more intuitive but that will have to be fixed in Itinero 2.

**Comment by JoeCooper** [comment]
It seems that if you're pointed at a dead end, it doesn't allow for a U-turn and it reports that no route is found. What do you think?

**Comment by xivk** [comment]
It should if you define a custom settings (it needs docs sorry):

https://github.com/itinero/routing/blob/develop/src/Itinero/RoutingSettings.cs#L60

You should be able to add a settings object for any call on the router.

**Comment by xivk** [comment]
There could be issues with for example dual carriage ways when using the angle approach. Think about a case of re-calculation combined with sub-optimal GPS coordinates. At the moment the steps are:

- Resolve to the closest road (could be the lane in the opposite direction).
- Route based on the angle (this could fail in the case of the opposite lane).

I'm also going to add an angle-based resolve that takes into account directions of driving per profile, so this should become:

- [ ] Resolve based on the direction and *multiple* closest roads within a predefined range.
- Route based on the angle.

This is already on my list for next week or so. I found the current state of things to already add enough value to merge.

A final solution would be to use map-matching of the last x-seconds of coordinates to really get a good idea of where the vehicle is driving taking into account the network.

**Comment by JoeCooper** [comment]
What should I be putting for T? Why is this generic?

**Comment by JoeCooper** [comment]
This looks like it's working for me.
