### ISSUE TITLE
RouterBase.Calculate and RouterBase.TryCalculate hang...

### ISSUE THREAD

**Issue by csancheztfs** [itinero/routing#172]
Hi, we are using Europe Route Data from OSM. The following coordinates hang TryCalculate method:

{10448880@50.8% [40.43434,-6.119286] }
    Attributes: {}
    EdgeId: 10448880
    Latitude: 40.4343376
    Longitude: -6.11928558
    Offset: 33277

{11716510@70.9% [40.4887,-6.0847] }
    Attributes: {}
    EdgeId: 11716510
    Latitude: 40.4887
    Longitude: -6.0847
    Offset: 46446

**Comment by xivk** [comment]
Sorry for the late reply, what profile are you using? Can you try adding the routing islands? It should check for unrealistic routes before starting calculations.

I'm testing Itinero 1.4 with the europe data to verify everything is working, any more feedback you can give me is potentially very valuable thanks!

**Comment by xivk** [comment]
Closing this, this should be fixed by either adding islands or contraction for the used profiles.
