### ISSUE TITLE
Dependencies Problem

### ISSUE THREAD

**Issue by pingurus** [itinero/routing#180]
Trying to import OSM Data via LoadOSMData() causes a System.IO.FileLoadException for me.
When I use protobuf-net version 2.0.0.668, the System.IO.FileLoadException is caused by a missing version 2.3.7.0, with an inner exception of a missing version 2.0.0.668
However, when I use version 2.3.7.0, the System.IO.FileLoadException is caused by a missing version 2.0.0.668, but only if not started from Visual Studio.
The exceptions occur in the same line.
I'm using Itinero 1.4.0-pre44 and OSMSharp 6.0.0 via Nuget and reinstall all packages when changing protobuf-net version.
This seems very odd to me, can you point me to a solution?

**Comment by pingurus** [comment]
When using the 2.3.7.0 version, I now get a 
ProtoBuf.ProtoException:
Unexpected end-group in source data; this usually means the source data is corrupt
in Visual Studio.

**Comment by xivk** [comment]
Thanks for reporting anyway, if there's anything we can do on our side to let us know. I checked and OsmSharp is the only dependency using protobuf and it uses one version. No conflict to be found in the Itinero packages AFAIK.

**Comment by pingurus** [comment]
I just found what (probably) causes the issue:
To use Itinero.IO.Osm v.1.4.0-pre44, I couldn't use the target framework .NET 4 as is, since Itinero has an indirect dependency of System.Net.Http, Version=1.5.0.0. I then upgraded to .NET 4.5 and since that point my described errors occur.

**Comment by pingurus** [comment]
I'll close it again since it is definitely not your fault.
I didn't copy the .config file to the directory I was running the program from.
