### ISSUE TITLE
Error when try to install itinero.IO.Osm nuget package

### ISSUE THREAD

**Issue by Overlordff** [itinero/routing#184]
Hello, I can't install Itinero.IO.Osm library and link with Xamarin.Android project. The problem with  some OsmSharp's dependency. Please, help me!

Error message:

Could not install package 'Microsoft.NETCore.Jit 1.0.2'. You are trying to install this package into a project that targets 
'MonoAndroid,Version=v8.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more 
information, contact the package author

**Comment by xivk** [comment]
I checked this, Itinero.IO.Osm supports netstandard1.6 and so does OsmSharp. That should be enough, not sure what is happening here. 

I don't have a xamarin setup to check myself. 

Also, you don't need Itinero.IO.Osm to do routing, just Itinero should be fine even if you use a routerdb loading with OSM data. Check the docs here:

http://docs.itinero.tech/docs/itinero/basic-concepts/routerdb.html#loading-a-router-db

**Comment by Overlordff** [comment]
Thanks for your responce. You can reproduce nuget error by creating new Android Blank project and trying to install Itinero.Io.Osm package (or just OsmSharp package). 
The problem chain of dependencies is:
https://www.nuget.org/packages/OsmSharp/
->
https://www.nuget.org/packages/Microsoft.NETCore.Portable.Compatibility/
->
https://www.nuget.org/packages/Microsoft.NETCore.Runtime.CoreCLR/
->
https://www.nuget.org/packages/Microsoft.NETCore.Jit/     (<---- The problem is here)

I decreased Android target version and it had no result. It looks like Microsoft.NETCore.Jit (and therefore Itinero.Io.Osm library) cannot be installed to Xamarin.Android project.

**Comment by xivk** [comment]
This is fixed now: https://github.com/OsmSharp/core/issues/59
