### ISSUE TITLE
build error: CS0117: 'Constants' does not contain a definition for 'NO_VERTEX'

### ISSUE THREAD

**Issue by jhidding** [itinero/routing#186]
Building on Debian/testing, using dotnet-sdk-2.1.4, I get the following errors

> Nodes/DynamicVehicleNodeTagProcessor.cs(129,41): error CS0117: 'Constants' does not contain a definition for 'NO_VERTEX'
> Restrictions/RestrictionProcessor.cs(153,41): error CS0117: 'Constants' does not contain a definition for 'NO_VERTEX'
> Streams/RouterDbStreamTarget.cs(121,46): error CS0117: 'Constants' does not contain a definition for 'NO_VERTEX'
> Streams/RouterDbStreamTarget.cs(145,42): error CS0117: 'Constants' does not contain a definition for 'NO_VERTEX'
>
> Build FAILED

more errors follow.

**Comment by xivk** [comment]
Strange... this is the develop branch I assume? I develop on Ubuntu 16.04 myself. There are no other errors and this is a clean clone?

**Comment by xivk** [comment]
Apologies, this is so obvious. Sorry about this, fixing now.
