### ISSUE TITLE
Itinero Xamarin Android

### ISSUE THREAD

**Issue by florinmarica** [itinero/routing#190]
Hello!
I'm trying to create a Xamarin Android app with offline map and routing using Osmsharp and Itinero.
I have a lot of problems with the plugins, i don't know if i'm doing the right way but i can't find an complete example.
My main 2 problems are: 
1. When I'm exploring the map some tiles dosen't load and i don't know how to debug this.
2.The route calculate method take a long time to execute for 2 point ( the coordinate for those 2 points are on the road).
 
Thanks!

**Comment by xivk** [comment]
There are two things you need to make sure you did on the mobile devices:

- Added a contraction hierarchy.
- Using the NoCache parameter when loading the routing data.

About the contraction there is more info here:

http://docs.itinero.tech/docs/itinero/basic-concepts/routerdb.html#contraction

About the no-cache thing, that's here:

http://docs.itinero.tech/docs/itinero/basic-concepts/routerdb.html#memory-mapped

About OsmSharp and it's UI, it's not supported anymore. We recommend you use Mapsui, it's way better and it's very actively maintained, it's the better choice :+1:

**Comment by florinmarica** [comment]
Thank you very much for the fast response. Now the route calculate very nice and fast. i will try the mapsui and see how it works. 
Thank you again!

**Comment by xivk** [comment]
Make sure you install the same packages... you can only use a router db in a later or equal Itinero version compared to the version it was created with.

**Comment by florinmarica** [comment]
Yes thank you, sorry for that, i use 14.0-pre53 for serialize. 
How can i add the route to mapsui map? i can't find anything.

**Comment by xivk** [comment]
There is no standard way but me and @pauldendulk have been discussing making a sample. I guess for now you have to convert the route object to a linestring and then you can add it to the map. 

Correct me if I'm wrong @pauldendulk

**Comment by pauldendulk** [comment]
It has been on my todo list for far too long. Ben, could you give me a few pointers. What is the todo list. Add the itinero nuget package. A specific one? What data to use? Which commands will I need?

**Comment by pauldendulk** [comment]
Ok. Let s do that. So which package do I use?

**Comment by florinmarica** [comment]
This is how i try to add the route to map, but i think i do something wrong because it doesn't show.  
`        private ILayer LayerRouteW(Route route)
        {
            List<Point> p = new List<Point>();
            foreach (Coordinate coordinate in route.Shape)
            {
                p.Add(new Point(coordinate.Latitude, coordinate.Longitude));
            }
            LineString ls = new LineString(p);
            Feature f = new Feature
            {
                Geometry = ls,
                ["Name"] = "Line 1",
                Styles = new List<IStyle> { new VectorStyle { Line = new Pen(Color.Red, 8) } }
            };
            return new MemoryLayer
            {
                Name = "Route",
                DataSource = new MemoryProvider(f),
                Style = null
            };
        }`

**Comment by pauldendulk** [comment]
@florinmarica What is this ```List p = new List();```? Reminiscence.Collections? What does your using look like?

**Comment by pauldendulk** [comment]
I am trying to get started, help me out: https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/ItineroRoutingSample.cs

**Comment by florinmarica** [comment]
i think the text was formated I'm using: List< Point > p = new List< Point >(); - Generic list

**Comment by xivk** [comment]
Don't use Reminiscense, that's just for Itinero use only... The code looks good, just add whatever is in the shape array to the map.

**Comment by xivk** [comment]
@pauldendulk Just installing the base Itinero package should be enough. If you want to load data from OSM in your sample all then also add Itinero.IO.Osm and you can load OSM data.

**Comment by pauldendulk** [comment]
@xivk @florinmarica My remark about reminiscense was just confusion that arose because something had gone wrong when pasting.

**Comment by pauldendulk** [comment]
@florinmarica If you use code then put it between back tics, these, top left keyboard: `
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting

**Comment by pauldendulk** [comment]
@xivk Could I do routing without data?

**Comment by pauldendulk** [comment]
Now it compiles
https://github.com/Mapsui/Mapsui/blob/master/Samples/Mapsui.Samples.Common/Maps/ItineroRoutingSample.cs

```c#
        private ILayer LayerRouteW(Route route)
        {
            List<Point> p = new List<Point>();
            foreach (Coordinate coordinate in route.Shape)
            {
                var spherical = SphericalMercator.FromLonLat(coordinate.Longitude, coordinate.Latitude);
                p.Add(new Point(spherical.X, spherical.Y));
            }
            LineString ls = new LineString(p);
            Feature f = new Feature
            {
                Geometry = ls,
                ["Name"] = "Line 1",
                Styles = new List<IStyle> { new VectorStyle { Line = new Pen(Color.Blue, 6) } }
            };
            return new MemoryLayer
            {
                Name = "Route",
                DataSource = new MemoryProvider(f),
                Style = null
            };
        }
```

**Comment by xivk** [comment]
Work is now ongoing in the Mapsui repo, getting back to this once 1.4 is released.

**Comment by pauldendulk** [comment]
ok
