### ISSUE TITLE
Question: Itinero support turn restriction with timezone

### ISSUE THREAD

**Issue by NguyenSen** [itinero/routing#197]
**Hello Team**
i want to know your library support turn restriction with timezone or not ?.
Ex; 6-8h or 16-19h no turn left with car or truck.

**Comment by xivk** [comment]
No, this is not supported, can you give me an example (on OSM perhaps)?

**Comment by NguyenSen** [comment]
@xivk  ex : https://www.openstreetmap.org/relation/87146

**Comment by xivk** [comment]
I added this to the Itinero roadmap as a possible future issue:

http://docs.itinero.tech/docs/itinero/development/index.html

Feel free te reopen if you have more questions about this, for now this is not supported, the only thing you can do is either include it or not include it.
