### ISSUE TITLE
Some questions/requests

### ISSUE THREAD

**Issue by weltmeyer** [itinero/routing#20]
Hi,

i am new to the mapping topic.

I have some questions:

## Can i build a routerdb for multiple vehicles at once?
i tried 
`routerDb.LoadOsmData(stream, Vehicle.Car, Vehicle.Bicycle, Vehicle.Pedestrian);`
which is generating okay.
But if it then use 
`routerDb.Calculate(Vehicle.Car.Shortest(), start, end);`
it generates a route though "service" highways or ways only for pedestrians.

## is it possible to multi-thread the LoadOsmData or speed it up other ways?
when doing this for full germany map(i know..its big...) its using one core 100% while my hdd mostly sleeps.

Thanks in advance,
jan

**Comment by xivk** [comment]
The code was built to support loading multiple profiles exactly as you are doing... about highway= service that's recently been added to the default car profile. What other invalid routes are you seeing?

About faster loading: the setup of the internal datastructure of the RouterDb doesn't allow multhreaded loading but a solution to faster updates is on the roadmap. For now this will have to do srry...

**Comment by weltmeyer** [comment]
Okay, have to describe it a little better:
i try to virtual move a vehicle along the path with respect to allowed speed.
if the highway is "service", the Car Vehicle is set to 5km/h which seems wrong to me.

I also see in code that 5 kmh is default speed for "service".

Maybe i am using the data wrong. Is there a better way to get speed for current branch?

My Code:
`

            foreach (var routePosition in _route)
            {
                Route.Branch branch = null;
                if (routePosition.BranchIndex < routePosition.Route.Branches.Length)
                    branch = routePosition.Route.Branches[routePosition.BranchIndex];
                if (branch != null)
                {
                    speed = Vehicle.Car.ProbableSpeed(branch.Attributes); //kmh
                    var service = "";
                    branch.Attributes.TryGetValue("highway", out service);
                }`






As of the multithreading: if it normally works to generate on routedb for all vehicles, i just have to generate the db data once and can load it after that :)

**Comment by xivk** [comment]
What is your usecase? If I know that I can usually help better.

The branches are the 'roads not taken' so not sure why you are requesting speeds there but yes, that is the correct way of working. And I think you are correct in saying that service should be a higher speed.

**Comment by weltmeyer** [comment]
Oh my... i used it totally wrong :)

I want to show the route on a gmap.net control:
`var routePoints = currentRoute.ToArray();
                        for (int routePointIndex = 0; routePointIndex < routePoints.Count() - 1; routePointIndex++)
                        {
                            var routePoint = routePoints[routePointIndex];

                            var brIndex = routePoint.BranchIndex;
                            if (brIndex > currentRoute.Branches.Length - 2)
                                break;


                            var branch = currentRoute.Branches[brIndex];
                            var nextPoint = routePoints[routePointIndex + 1];
                            string streetname = "";
                            if (branch.Attributes.TryGetValue("name", out streetname))
                            {
                                /* if (streetname.ToLower().Contains("hauptstraße"))
                                     System.Diagnostics.Debugger.Break();*/
                            }

                            var speed = Vehicle.Car.ProbableSpeed(branch.Attributes);

                            var shape = currentRoute.Shape[routePoint.Shape];
                            var shapeMeta = currentRoute.ShapeMeta[routePoint.MetaIndex];

                            var branchRoute = overlay.Routes.SingleOrDefault(r => r.Name == $"branch_{brIndex}");
                            if (branchRoute == null)
                            {

                                var colors = new Dictionary<int, Color>()
                                {
                                    {0,Color.Red },
                                    {5,Color.Blue },
                                    {10,Color.Yellow },
                                    {30,Color.Orange },
                                    {50,Color.YellowGreen },
                                    {70,Color.Green },
                                }

                                ;



                                branchRoute = new GMapRoute($"branch_{brIndex}");
                                branchRoute.Stroke = (Pen)branchRoute.Stroke.Clone();

                                branchRoute.Stroke.Color = Color.Green.Interpolate(Color.Red, Math.Min(speed,100.0) * (1.0 / 100.0)); //colors.Where(c => c.Key <= speed).OrderByDescending(c => c.Key).First().Value;
                                overlay.Routes.Add(branchRoute);
                            }

                            if (!branchRoute.Points.Any(p => p.Equals(new PointLatLng(shape.Latitude, shape.Longitude))))
                                branchRoute.Points.Add(new PointLatLng(shape.Latitude, shape.Longitude));
                            if (nextPoint.BranchIndex != routePoint.BranchIndex)
                            {
                                var nextShape = currentRoute.Shape[nextPoint.Shape];
                                if (!branchRoute.Points.Any(p => p.Equals(new PointLatLng(nextShape.Latitude, nextShape.Longitude))))
                                    branchRoute.Points.Add(new PointLatLng(nextShape.Latitude, nextShape.Longitude));
                            }`



i thought the branches were the actual way...


so if i want to do it right,

i should just foreach (Routepoint rp in route) ?
and then get the point with route.shapes[rp.shape]?

**Comment by weltmeyer** [comment]
Okay. got it working! thank you very much!

**Comment by xivk** [comment]
You can also convert the route to GeoJSON if that helps... never used the gmaps.net control.

:+1: that you got things working!

**Comment by weltmeyer** [comment]
Hi again, 

If i use:
 ```
 using (var stream = new FileInfo(RouterFile).Open(FileMode.Open,FileAccess.ReadWrite))
                    {
                        var memoryMap = new MemoryMapStream(stream);
                        _routerDb = new RouterDb(memoryMap,RoutingNetworkProfile.Default);
                    }

```
then i cant use the routerDB because _supportedProfiles is empty... am i doing it wrong again?

**Comment by xivk** [comment]
To do this use the RouterDb.Deserialize method with an argument to indicate you want to use a memory map:

https://github.com/itinero/routing/blob/develop/src/Itinero/RouterDb.cs#L524

Like:
 ```
var db = RouterDb.Deserialize(stream, RouterDbProfile.NoCache);
```
The NoCache config is best in 90% of usecases.

**Comment by xivk** [comment]
In this case you need to keep the stream open during the lifetime of the RouterDb.

**Comment by xivk** [comment]
Did you manage to get this done?

**Comment by weltmeyer** [comment]
yep. got this working, tyvvm :)
and its still really fast. maybe i can generate a world.routerfile with this and put this together into a webservice, so my app doesnt need to bring the x GBytes of routerdb with it :)

Currently, the germany.routerdb is about 1,1GB... so the world-wide maybe is much bigger.

**Comment by xivk** [comment]
The filesizes could be smaller, it's still uncompressed data. Part of it needs to stay that way but some of the attributes/streetnames can be compressed. I haven't done that yet but it's on the roadmap.

Processing the entire world is possible but it takes a while and it has been a while since my last try.

**Comment by xivk** [comment]
I'm closing this issue. There is a planet-wide file available here but it's only for car routing and doesn't contain a contracted graph:

http://files.itinero.tech/data/itinero/routerdbs/
