### ISSUE TITLE
Road Restrictions

### ISSUE THREAD

**Issue by wmpoolt** [itinero/routing#204]
Hi !

I want to restrict in my route.

For Example;

There are 3 bridges between two points. 

Name of the first bridge X
Name of the second bridge Y
Name of the third bridge Z

If I have a bigTruck, i want to go to X Bridge.
Else if I have a SmalTruck , i want to go to Y Bridge
Else i want to go to Z Bridge.

Actually, i searched to lua script. But i don't know, how can i do in itinero ?

Can you help me please ?

**Comment by wmpoolt** [comment]
Hi Again !

I want to make a statement to make it clearer.

I live in İstanbul(Turkey.)

There are 3 bridges and tunnel linking Anatolia and european continents in Istanbul.

YSS Bridge, FSM Bridge and Bogazici Bridge, Eurasian Tunnel

BigTruck never cross the FSM Bridge and Bogazici Bridge

Smalltrucks never cross the Bogazici Bridge and Eurasian Tunnel but  Smalltrucks can pass through the YSS but are not preferred because this is paid.

Cars can pass through the all bridges and tunnel but are not preferred because they are paid. And cars usually use the first bridge.

**Comment by xivk** [comment]
Sorry for the late reply, I recommend you read of the routing profiles here and build your own specific for these issue:

https://docs.itinero.tech/docs/itinero/basic-concepts/profiles/lua.html
