### ISSUE TITLE
NETSTANDARD20 Constant is not defined in netstandard2.0 build

### ISSUE THREAD

**Issue by jonwagner** [itinero/routing#210]
I noticed that the NETSTANDARD20 constant isn't defined for netstandard2.0 builds. This results in `FastHierarchyBuilder.InitializeWitnessGraph` to not use multi-threaded operations.

I suggest adding the following to Itinero.csproj:

```
  <PropertyGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <DefineConstants>$(DefineConstants);NETSTANDARD20;NETFX_CORE;DOTNET_CORE</DefineConstants>
  </PropertyGroup> 
```

**Comment by airbreather** [comment]
Alternative suggestion: pretty sure the SDK defines `NETSTANDARD2_0` (notice the underscore) for .NET Standard builds.

**Comment by xivk** [comment]
Ok, thanks for the suggestions :+1:

**Comment by xivk** [comment]
@airbreather Are you sure about this, I can't find any docs on this.

**Comment by jonwagner** [comment]
There's another one at line 470 in FastHierarchyBuilder.

https://github.com/itinero/routing/blob/e7f1d8719d29fdb6bf31e11f1537242e76e25141/src/Itinero/Algorithms/Contracted/FastHierarchyBuilder.cs#L470

**Comment by xivk** [comment]
Hmmm, thanks, missed that one!
