### ISSUE TITLE
Question: fastest method to get edges contained in an area

### ISSUE THREAD

**Issue by alecava58** [itinero/routing#216]
What would be the fastest method to get the edge ids contained in an area. The area could be a circle or a polygon.

The method could be:
uint[] GetEdgesInCircle(GeometricGraph _graph, Coordinate center, int radiusInMeter)
or
IList<RoutingEdge> GetEdgesInCircle(GeometricGraph _graph, Coordinate center, int radiusInMeter)

or
uint[] GetEdgesInPolygon(GeometricGraph _graph, Polygon _polygon)

or RoutingNetwork extension

**Comment by xivk** [comment]
This could be a nice addition to the API, what is you usecase? Perhaps to get this done using the current version you can look at the routerdb extension methods like this one:

https://github.com/itinero/routing/blob/develop/src/Itinero/RouterDbExtensions.cs#L1527

**Comment by xivk** [comment]
Closing this as it seems to be answered now. Feel free to reopen if you still have related questions.
