### ISSUE TITLE
Building the whole US router db failed.

### ISSUE THREAD

**Issue by Casper-ThinkGeo** [itinero/routing#218]
Hi, I'm working on building the whole US router db. There is an "Index was outside the bounds of the array" exception has been thrown by "Compress" method on the lines 641 of DirectedGraph class:
![exception](https://user-images.githubusercontent.com/16750463/44650849-53680e00-aa1a-11e8-9dd9-3278ac464062.PNG)

I try to load all US states .pbf files to building a router db as following diagram:
![folder](https://user-images.githubusercontent.com/16750463/44651182-341db080-aa1b-11e8-9955-3fe308e6247c.png)

After I added a "Car.Fastest" contraction, the exception has been thrown when the router db is being serialized to a file. I haven't any idea on this issue. Could you give me some help so that I can completely build the whole US router db?

Thanks,
Casper .Lee

**Comment by xivk** [comment]
What version of Itinero are you using?

**Comment by Casper-ThinkGeo** [comment]
I'm working on the develop branch source code. The index out of range exception has thrown in compress method when the RouterDb is serializing to a router db file.

Thanks,
Casper. Lee

**Comment by xivk** [comment]
This has been fixed now.
