### ISSUE TITLE
Heatmap errors

### ISSUE THREAD

**Issue by F0rt1s** [itinero/routing#22]
Hello!
I am trying to calculate a heatmap from a resolved point, but I get strange results.
For example the following heatmap for a point in Berlin: [Example](http://maschine.online/HeatmapTest.html)  (the color represents the travel time in seconds). As you can see there are some errors in the border areas. You suddenly get low travel times (green dots) in an area far away from the start point. I am using current OSM data and the car profile. Any ideas why this might be happening?

**Comment by xivk** [comment]
Hmm, no idea, what is the code you're using to calculate this? Are you using the Heatmap extension method?
