### ISSUE TITLE
Question: Dynamic weight in contracted mode

### ISSUE THREAD

**Issue by uu3474** [itinero/routing#233]
Hi, itinero is nice project and very help me with my problems.
I'm trying to make routing with traffic jam. With my own implement of _WeightHandler_. It's works fine without contacted mode, i can easily get edge id and edge profile id. But in contacted mode, graph is different, and edges ids is different too. How can i convert contracted edge to obvious edge? Is this possible?

**Comment by uu3474** [comment]
i use ExpandEdge, that is DirectedMetaGraph extension, maybe this help someone

**Comment by xivk** [comment]
This is not possible with the current implementation of contraction hierarchies. We do plan a solution for this using customizable contraction hierarchies but we can't really say yet when we have this done.
