### ISSUE TITLE
Can not find the closest coordinate of the route

### ISSUE THREAD

**Issue by mgarzon62** [itinero/routing#235]
I need the point of the route closest to my coordinate.
I've tried it with the Resolve method and it returns the same coordinate that I give it but not the closest one to a route.

How can I get it?

**Comment by Sonnenspeer** [comment]
This issue should be the same https://github.com/itinero/routing/issues/221

**Comment by xivk** [comment]
Yes, as @Sonnenspeer mentioned, you can do this with the extension methods for the route class.
