### ISSUE TITLE
Wrong Way

### ISSUE THREAD

**Issue by damiendevc** [itinero/routing#237]
I using v.1.4.0-pre92 with BigTruck standard profile and TryCalculateTSP, calculated route between 3 point is wrong: 
![way](https://user-images.githubusercontent.com/46826778/51411124-06bad600-1b67-11e9-8544-7730d30cd651.png)
Full GEOJSON is:
[wrongway_geojson.txt](https://github.com/itinero/routing/files/2774375/wrongway_geojson.txt)
What can be wrong ?

**Comment by damiendevc** [comment]
I calculate this route for 4 points:
Start from (Lat:54,2937316894531 Lon:18,8042392730713) 
via (Lat:54,3493499755859 Lon:18,681619644165)
via (Lat:54,3613166809082 Lon:18,6928615570068)
Stop at (Lat:54,2937316894531 Lon:18,8042392730713) - exactly the same as Start
Please help.

**Comment by xivk** [comment]
This does not seem to happen in Itinero:

![image](https://user-images.githubusercontent.com/1128068/54072169-de01b380-426e-11e9-95d6-be0ca8f36079.png)

http://geojson.io/#id=gist:xivk/7228be96ac7f5acf75a99c68303e3fd0&map=13/54.3273/18.7459

Perhaps this is an issue in Itinero.Optimization. Logging an issue there instead.

**Comment by Shkarface** [comment]
I always get routes like this on contracted graphs, this does not occur on non-contracted graphs!
The green polyline uses the default "car.classifications" profile with contraction, the routerdb is built from an osm file using a another service and its consumed by the another service for routing



![Screenshot from 2019-12-07 09-51-43](https://user-images.githubusercontent.com/1114849/70370369-9bd9d100-18d7-11ea-8556-c4c39e8827fb.jpg)
