### ISSUE TITLE
Ordering multiple stops in route (courier service)

### ISSUE THREAD

**Issue by funkinater** [itinero/routing#239]
Hello, there appears to be limited information out there about Itinero related to my particular need and I'm hoping someone can help. I would like to feed a list of lat/long coordinates into Itinero and have it return an optimized, ordered list of stops that will assist a driver complete his route faster and while using less fuel.

In our real-world use case, our drivers are delivering to an average of 30-35 addresses in their "route" every day, and the addresses are not on a specific set route (just in a general area covering several zip codes).

Can this be done with Itinero? Any assistance would be greatly appreciated!

**Comment by alecava58** [comment]
Hi, the functions you need is inside Itinero.Optimization library. Take a look at TSP classes.

**Comment by xivk** [comment]
Thanks @alecava58 for answering this! :+1: 

Yes, check out [Itinero.Optimization](https://github.com/itinero/optimization), feel free to open another issue there if you have any other questions. 

We also assist companies in implementing this, if you need direct support, feel free to get in touch with us via this form:

http://www.itinero.tech/#contact
