### ISSUE TITLE
Bug when using proseccRestrictions with LoadOsmData

### ISSUE THREAD

**Issue by TomQv** [itinero/routing#254]
`void LoadOsmData(this RouterDb db, Stream data, bool allCore = false, bool processRestrictions = true, params Vehicle[] vehicles);`

Using this overload with car, pedestrian, bicycle and processRestrictions =true is resulting in a routerdb with only car inluded. Pedestrian and bicycle are gone.

Same call with  processRestrictions =false, routerdb is fine.

**Comment by xivk** [comment]
Trying to reproduce this with:

```
            var routerDb = new RouterDb();
            using (var stream = File.OpenRead(Download.LuxembourgLocal))
            {
                routerDb.LoadOsmData(stream, false, true, Itinero.Osm.Vehicles.Vehicle.Car, Itinero.Osm.Vehicles.Vehicle.Pedestrian,
                    Itinero.Osm.Vehicles.Vehicle.Bicycle);
            }
```
I get this in the routerdb:

![image](https://user-images.githubusercontent.com/1128068/54911251-f6680400-4ee5-11e9-8031-ec0bc923fa70.png)

**Comment by TomQv** [comment]
Strange, I also can't reproduce it anymore. Did you fix something in the meantime?
Its possible, that I had the issue with an older version.
Yesterday I upgraded to the latest Itinero to test this #253

**Comment by xivk** [comment]
This gets tested in almost the same way in the functional tests every build so this should be fine but I'll keep an eye on this.

Also, make sure to manually select the correct package. We've gotten to the bad situation again where the prerelease # exceeds 100, nuget handles this as < 99

**Comment by TomQv** [comment]
oups... maybe you should go to 1.4.1-pre001 or so....

![grafik](https://user-images.githubusercontent.com/6605960/54913730-b27bfb80-4ef3-11e9-982c-6a0d8acef5b9.png)

**Comment by xivk** [comment]
Yes, it's a mess, the thing is that it should never have gotten to 100 in the first place. Working hard to finally release 1.4.0 stable as you may have noticed.

**Comment by TomQv** [comment]
> Working hard to finally release
I know exactly what you mean...
