### ISSUE TITLE
Problem with latest pre-release

### ISSUE THREAD

**Issue by t22dk** [itinero/routing#27]
I'm having problems using the latest pre-release nuget package.

I get this error, and can't seem to cast my way out of it.

Its just the WIKI example code.

![image](https://cloud.githubusercontent.com/assets/20927781/20341964/bc022b08-abe8-11e6-934b-4a825955f285.png)

Is this a bug, or have i just misunderstood something ?

**Comment by xivk** [comment]
Do you have the latest version for both Itinero and Itinero.IO.Osm?

**Comment by t22dk** [comment]
I think so, both are 0.30.0-rc1
I get ambiguous reference, with Vehicle is in both Itinero.Osm.Vehicles.Vehicle and ind Itierno.Profiles.Vehicle

**Comment by t22dk** [comment]
I think i have messed something up.

Will try to reinstall. 

Thanks.

**Comment by xivk** [comment]
The ambiguous reference is normal just use or remove the Itinero.Profile using:

> routerDb.LoadOsmData(stream, Itinero.Osm.Vehicles.Vehicle.Car);
