### ISSUE TITLE
Routed path does not match exactly with the path's of source of routing(shapefile)

### ISSUE THREAD

**Issue by drspam1991** [itinero/routing#270]
Hi,
I run the "Sample.Shape" sample and the result route path, does not match exactly with the source. How can i tell the routing to use match coords with points in source shape file?

Red line is route result:
![Capture](https://user-images.githubusercontent.com/6633208/59024289-def2b300-8866-11e9-89da-eb27c3bf9f3a.PNG)

Thank you.

**Comment by AndersHGP** [comment]
Probably related to this #120

**Comment by drspam1991** [comment]
@AndersHGP 
Thank you for replay. I fix this by change Coordinate class (latitude, longitude) from float to double, and also all affected classes.
