### ISSUE TITLE
Route could not calculate

### ISSUE THREAD

**Issue by bobland1** [itinero/routing#286]
We have a dentist finder tool, whereby you pass it the area u wanna look. We get that area, put it as the start point and then we will find all our dentists nearby and route to them. Providing the distance the dentist is from the start point.

With certain postcodes it can't calculate a route, but putting the same details into OSM and using their route calculator it works.

Startpoints that don't work: 
1 - NN12 6XP
`A route for Startpoint: [52.12233, -0.9994654] RouterPoint: [52.13091, -0.99052] could not be calculated.`
2 - SE1 **
`A route for Startpoint: [51.50183, -0.090951] RouterPoint: [51.53262, -0.1064862] could not be calculated.`
3 - EN2 0AW
`A route for Startpoint: [51.65919, -0.082791] RouterPoint: [51.6583, -0.20287] could not be calculated.`

It then throws a 'Itinero.Exceptions.RouteNotFoundException'

**Comment by xivk** [comment]
Sometime there are islands in the network, try adding island detection to the preprocessing of you routerdb.

**Comment by bobland1** [comment]
How is this done, the documentation is quite hard to understand

**Comment by xivk** [comment]
There should be an extension method on the routerdb to add islands (like here: https://github.com/itinero/idp/blob/develop/src/IDP/Switches/RouterDb/SwitchIslandsRouterDb.cs#L82) or when using IDP add the --islands switch before writing the routerdb to disk.

**Comment by bobland1** [comment]
Alright, ill give it a go. Might be wise to make this a default

**Comment by xivk** [comment]
Yes, already on the roadmap but it would be a breaking change for some usecases so we wait until another major release.

**Comment by bobland1** [comment]
That worked! Cheers

**Comment by bouldrini** [comment]
That worked for me too after 2 days of researching. Important information.
In my optinion you should at least add a note to othe docs...
