### ISSUE TITLE
router.Calculate throw NotfoundExepction

### ISSUE THREAD

**Issue by VerSooSet** [itinero/routing#318]
1. I just open website openstreetmap.org
2. Has set two points and chooise option car route. Build a route succesfully.
3. Has created a new .Net Core Console Application
4. Get a code snippet from Itinero documentation and build only car routes file base on .osm file 
5. Get points coordinates of step 2. and push to float variables **start** and **end** like "as-is" at this:
`route = router.Calculate(profile, start, end);` 
6. when Itinero try to calculate a route it returns RouteNotfoundExepction

**Comment by juliusfriedman** [comment]
This post barely makes sense.

It sounds like you didn't get the right OSM or you didn't have the right data in your OSM or perhaps your not using an OSM no one knows because you didn't provide reliable instructions on how to replicate your issue.. read it again and see if you can from that list.

**Comment by VerSooSet** [comment]
thank you. I repeated my steps and get a success using the coordinate data for the Canadian territory. It looks like a problem with a osm-file gets by [geofabrica.de](geofabrica.de) source. So a wrong data was at file by website region at the Russia territory.
