### ISSUE TITLE
Custom Profiles

### ISSUE THREAD

**Issue by kevin-work** [itinero/routing#32]
I was looking for a way to change the speed of vehicles, possibly through the use of a factor and I came across the Wiki on Profiles with the use of Lua scripts. So if I define a custom script, how do I add it to the RouterDB? Am I misunderstanding this in that it is info for modifying Itinero itself? If so is there an easy way to modify vehicle speeds?

**Comment by xivk** [comment]
I updated the wiki page a bit:

https://github.com/itinero/routing/wiki/Profiles#build-a-routerdb-with-embedded-vehicles

**Comment by kevin-work** [comment]
Ahh thanks very much. Exactly what I needed.

**Comment by kevin-work** [comment]
In terms of the speed, do I have to regenerate the routing file every time I change the profile?

**Comment by xivk** [comment]
Yes, and no, you can add a new profile to the routerdb but then you have to absolutely sure all tags and attributes you want are properly loaded using another profile. Just use this code:

`routerDb.AddSupportedVehicle(vehicle);`

You do need to re-contract any contracted graphs you built before.

**Comment by xivk** [comment]
@kevin-work Closing this issue, feel free to repopen if any questions.
