### ISSUE TITLE
Calculating route based on points of interest

### ISSUE THREAD

**Issue by kaspermm** [itinero/routing#339]
Hello, 
I am trying to use Itinero for calculating a route, where it should base the route on the location of charging stations for cars. 
I dont want it simply calculate the route from Point A to to the charging station, but rather from point A to point B, where it suggest a route based on if  there are charging stations along the route. 

What is the best way to do this? Is it to make a custom profile, which is based on the 'cars' profile and adding some heurestics, or is there a better way?

**Comment by xivk** [comment]
This is non-trivial and not a feature that is built in to Itinero. I think this is more a feature for this package:

https://github.com/itinero/optimization

But even in that one there is no ready-to-use solution yet. If you want a 'perfect' solution meaning one that truly returns the shortest or fastest route with minimal charging then I suggest adapting the STSP solution (selective travelling salesman) and expand it to use as little charging as possible given a maximum travel distance. 

As a quick solution, a heuristic, could be to first calculate the route and then find charging stations close to the first maximum distance on the route where charging is needed. Calculate a route to that station, then calculate a route to the destination again and repeat the process until the destination is in range.

We also do consulting around Itinero, if you need expert assistance from us that is also possible! Hope this helps! 👍

**Comment by kaspermm** [comment]
Thanks for the quick and thorough reply, it helps a lot!

I wil definitely look into this, it was a huge help!

I might contact you again, regarding expert assistance.

Best regards.
