### ISSUE TITLE
I can calculate the route for a passenger?

### ISSUE THREAD

**Issue by GioAlba** [itinero/routing#36]
Hi, I would like to ask a question.
I would use Itinero to have the route for a passenger (and not for a vehicle) to go from a stop A to a stops B. Is it Possible?
The road is made by a bus and need to do the least possible stopovers. I have available GTFS. How could I tell the system to calculate the shortest path and at the same time the way in which the passenger changes less often means of transport?
Thanks

**Comment by xivk** [comment]
There is this: 

https://github.com/itinero/transit 

It's being used in several projects already but it's not in any way feature complete and still a bit rough around the edges.

I can help you with a basic setup.

**Comment by GioAlba** [comment]
Thank you. would you be very kind. At least to understand where to start. All the progress that I will be shared

**Comment by GioAlba** [comment]
Hi can you help me with a basic setup

**Comment by xivk** [comment]
I did a quick update of the transit project to make sure it works with the latest Itinero. You can follow this code in the functional test project:

https://github.com/itinero/transit/blob/develop/test/Itinero.Transit.Test.Functional/Program.cs#L49

Basically:

1. Create or load an Itinero routerdb for the area of the transit operator.
2. Load GTFS feed.
3. Create on multimodal db that embeds the two together.
4. Sort connections.
5. Use the multimodal router.

Please log issues about this from now on in the transit project repo 👍
