### ISSUE TITLE
Location could not routed to or from.

### ISSUE THREAD

**Issue by HeuHax** [itinero/routing#42]
I get this error often, but this behaviour is horrible to work with.

I would like to get it to find the nearest point to route to instead of just throwing an error.
Our scenario doesn't demand that high accuracy, so i would be nice to just get the nearest point.

Is this possible somehow?

Look at how this works for instance:
http://map.project-osrm.org/?z=17&center=56.091145%2C8.247771&loc=56.090924%2C8.245631&loc=56.127293%2C8.508650&hl=en&alt=0

**Comment by xivk** [comment]
You can do this by 'resolving' a location first and then calculating a route.  You can use this method to get a routerpoint for each location:

Router.Resolve(): https://github.com/itinero/routing/blob/develop/src/Itinero/RouterBaseExtensions.cs#L196

With this method you can set the maximum distance parameter. And then calculate a route using this:

Router.Calculate(): https://github.com/itinero/routing/blob/develop/src/Itinero/RouterBaseExtensions.cs#L239

I'll add a TODO here to increase this distance by default if a location couldn't be found. Similar to what OSRM does. Better return something than nothing?

- [ ] Increase resolving distance when fails.

Note that you can also use Router.TryResolve(). This won't lead to an exception but you can check the result and see if it's valid. Then increase the distance parameter and try again.

**Comment by HeuHax** [comment]
Hey thanks for your fast reply!

I actually have tried that, but i still get route not found exception.

This is the two points i try route to/from as an example.
http://map.project-osrm.org/?z=18&center=56.090140%2C8.245953&loc=56.160633%2C8.123179&loc=56.090697%2C8.245347&hl=en&alt=0

What i see here is that it is a "pedestrian street", maybe that has something to do with it ?
But still it should get the closest point...

**Comment by xivk** [comment]
If you use the 'car.fastest()' profile it shouldn't resolve on a pedestrian street.... I'll try it out and figure out what's going on.

**Comment by xivk** [comment]
Ok, now that I look at it in a bit more detail, it's resolving to this small segment:

http://www.openstreetmap.org/way/27717018#map=19/56.09055/8.24614

There is an 'island detection' algorithm already there in Itinero. I'll see if I can make this a default post-processing step and make sure not to resolve to small islands like this.

- [ ] Check for small islands and don't resolve there.

**Comment by xivk** [comment]
Oh, and thanks for the effort of reporting these issues!

**Comment by HeuHax** [comment]
I am using the car.shortest profile because we need to sort a lot of points by distance, which is why i'm also using the Weight method :)

I'm the one thanking for a great library :)

**Comment by HeuHax** [comment]
Hey Ben, do you have an ETA on this ? :)

**Comment by xivk** [comment]
Still thinking about how to best fix this issue without changing too much. This one is not that easy to fix... 👍 

There is a tradeoff between adding extra tags to the island segments and use them to not resolve there or adding something dedicated that labels these segments as islands and do the same. The first option is easier but would expose the island labels to the outside as extra tags that weren't there before making it a bit inconsistent and 'hacky'.

Still weighing the options but I shouldn't be long until I come up with something acceptable.

Something I could do in the meantime is to add the island detection option to the resolving code so it would work like this:

- Resolve a point.
- Check for an island (a minimum number of connected vertices for example)
  - YES, an island: start over and choose another point.
  - NO: return the location.

This would be independent of the preprocessing but would impact performance when resolving. Also means this would be optional, turned off by default until something permanent can be built.

**Comment by xivk** [comment]
Oh, something like this already exists, to detect an 'island':

https://github.com/itinero/routing/blob/develop/src/Itinero/RouterBase.cs#L62

So it would be a matter of writing a couple of lines of code to check this for each resolved option.

**Comment by xivk** [comment]
DISCLAIMER: untested code below!

```
        /// <summary>
        /// Resolves a location but also checks if it's connected to the rest of the network.
        /// </summary>
        public static RouterPoint ResolveConnected(this RouterBase router, IProfileInstance profileInstance, float latitude, float longitude, float radiusInMeter = 1000,
            float maxSearchDistance = Constants.SearchDistanceInMeter)
        {
            return router.TryResolve(new IProfileInstance[] { profileInstance }, latitude, longitude, (edge) =>
            {
                // create a temp resolved point in the middle of this edge.
                var tempRouterPoint = new RouterPoint(0, 0, edge.Id, ushort.MaxValue / 2);
                var connectivityResult = router.TryCheckConnectivity(profileInstance, tempRouterPoint, radiusInMeter);
                if (connectivityResult.IsError)
                { // if there is an error checking connectivity, choose not report it, just don't choose this point.
                    return false;
                }
                return connectivityResult.Value;
            }, maxSearchDistance).Value;
        }
```

This is an extension method that use only the current state of the code to check each resolved point for connectivity. You can manually set the radius to use and you can first calculate routes without this check, and then, if the calculation fails, try again but then use this method to resolve the locations. This should minimize performance impact.

The method should give you identical points when they are connected anyway, only different ones when the closest location is unconnected. Also make sure to make _maxSearchDistance_ large enough to find locations that are connected.

Not sure if I'm going to include this in Itinero by default or if I'm going to thing about a better alternative solution but at least this should get you started.

**Comment by HeuHax** [comment]
Looked so promising! Sadly it doesn't seem to work :(

It just returns the same point as if it actually is connected to something. Maybe it is, but that connection isn't working...
https://www.google.dk/maps/place/56%C2%B005'26.2%22N+8%C2%B014'43.6%22E/@56.09062,8.2448978,19z/data=!3m1!4b1!4m5!3m4!1s0x0:0x0!8m2!3d56.09062!4d8.245445

**Comment by xivk** [comment]
Closing this issue, I added and tested a new version of the code above to the latest Itinero version. Hope this is still usefull...

**Comment by mgarzon62** [comment]
Hi Ben
That code is returning the same point to me as if it were connected to something but not. I need the point of the route closest to my coordinate.

How can I get it?

**Comment by DMXS33** [comment]
Hi, 
I also have problem with this issue. I checked everything but without success. Here is my sample: 
Profile _car = Itinero.Osm.Vehicles.Vehicle.Car.Fastest();
List<Coordinate> locations = new List<Coordinate>();
locations.Add(new Coordinate(42.7358f, 23.259f));          
locations.Add(new Coordinate(42.66542f, 23.29363f));            
var location = new Coordinate(42.6929281f, 23.3237417f);  //problematic point 

var point = router.TryResolveConnected(_car, location, 200, 200);
locations.Add(new Coordinate(point.Value.Latitude, point.Value.Longitude));

MassResolvingAlgorithm massResolver = new MassResolvingAlgorithm(router, new Itinero.Profiles.Profile[] { _car }, locations.ToArray(), maxSearchDistance: 200f);

var matrixCalculator = new Itinero.Algorithms.Matrices.WeightMatrixAlgorithm(router, _car, massResolver);
matrixCalculator.Run();

//matrixCalculator.Errors contains an error: Code	NotRoutable, Message	"Location could not routed to or from."	- about the last point 42.6929281f, 23.3237417f

https://www.google.bg/maps/dir/42.6929281,23.3237417/ - you can see that this point has a few pedestrian meters. I guess this is the problem. I thought that TryResolveConnected will return the nearest coordinate that is accessible by car. 
I'm using version 1.5 of the library and the latest version of 'bulgaria-latest.osm.pbf'

How should I resolve this problem ? 

Thank you!

**Comment by DMXS33** [comment]
I found the answer myself :-)

**Comment by burakmercan34** [comment]
Can you share your answer please @DMXS33 ?
