### ISSUE TITLE
Itenero Exception 

### ISSUE THREAD

**Issue by SAADZAMIR** [itinero/routing#44]
An unhandled exception of type 'System.Exception' occurred in Itinero.dll

Additional information: Cannot deserialize geometric graph: Invalid version #: -1

**Comment by xivk** [comment]
A few things you can check:

- Is the file really a routerdb created by Itinero.
- Has the file been properly written by Itinero, including flushed to disk.

When loading OSM files you should follow this procedure:

https://github.com/itinero/routing/wiki#example

**Comment by xivk** [comment]
Assuming this is ok, closing, feel free to reopen when something still not clear.
