### ISSUE TITLE
FirstPass for nodes doesn't get executed on TwoPassProcessor

### ISSUE THREAD

**Issue by alecava58** [itinero/routing#48]
I have a custom TwoPassProcessor with a FirstPass for nodes and a SecondPass for ways functions.
Before a certain release (I can't say which one) the FirstPass for nodes function get executed, now it doesn't.
I moved the logic in the SecondPass for nodes function and there is executed.

**Comment by xivk** [comment]
Hmmm ok, I used to tell OsmSharp to skip nodes in the first pass because I don't use they. You do use them? No way you can do what you need in the second pass?

**Comment by xivk** [comment]
Oh, and I recently fixed an Issue in OsmSharp that prevented it from actually skipping the nodes, making loading the files way faster.

**Comment by alecava58** [comment]
I moved the code on SecondPass for nodes and it seems to be ok because the SecondPass for nodes get executed before the SecondPass for ways.

**Comment by alecava58** [comment]
If the SecondPass for nodes is ALWAYS executed before the SecondPass for ways for me is ok.

**Comment by xivk** [comment]
Yep, that exactly right. I should:

- [ ] Remove the FirstPass(node) option or add someting to get implementers to force the firstpass nodes.

**Comment by alecava58** [comment]
Ok for me.

**Comment by xivk** [comment]
Reopening because it has a TODO
