### ISSUE TITLE
Calculating route on a straight road can produce invalid GeoJSON.

### ISSUE THREAD

**Issue by CedricLCB** [itinero/routing#5]
See attachment for a route between:
latlng: 50.8587, 5.493034
latlng: 50.8583, 5.488124

Attached is the output using route.ToGeoJson()
The Linestring-feature only contains 1 point, which is invalid according to http://geojsonlint.com/
I suppose this is because the route was generated on a straight road with no "waypoints" (in the osm-file) between the chosen coordinates.

[json.txt](https://github.com/itinero/routing/files/327527/json.txt)

**Comment by xivk** [comment]
Thanks! Definitely a bug, a route should always include minimum of two points. Two things to do:

- [ ] Have GeoJSON code check for invalid LineStrings (with only one coordinate).
- [ ] Check why route in this case has only one coordinate.

**Comment by xivk** [comment]
A small issue in the route builder, now this is the output:

http://geojson.io/#id=gist:anonymous/bfce365041f22678495c36a067e44eb3&map=16/50.8575/5.4900
