### ISSUE TITLE
RouteNotFoundException

### ISSUE THREAD

**Issue by amarinsek** [itinero/routing#56]
I have a simple test to calculate routes between random vertices. Approximately 10% of route calculations throws exception Itinero.Exceptions.RouteNotFoundException while OSM/OSRM routing returns valid route.

For example:

OSM data: slovenia-latest.osm.pbf

https://www.openstreetmap.org/directions?engine=osrm_car&route=46.50853,15.07739;46.24624,14.35322
https://www.openstreetmap.org/directions?engine=osrm_car&route=46.43107,14.07973;45.88519,14.43405
https://www.openstreetmap.org/directions?engine=osrm_car&route=45.57986,15.19478;46.12383,15.57374

**Comment by xivk** [comment]
Thanks again for test, will check this....

Just to make sure, you mean random 'vertices' not random locations right? And did you also load other profiles? Did you use a contracted version for the car profile?

**Comment by amarinsek** [comment]
Yes, I mean random vertices, so the problem is not in resolving locations but in route calculations. I used contract for the built-in car profile as well as a contract for my OSRM like car profile (same as a car, but with speed_profile / ["track"] = 30 commented out).

**Comment by xivk** [comment]
Perhaps related to #52

**Comment by xivk** [comment]
Can you share the core you use to test or at least the code you use to build the routerdb? And the lua profile?

**Comment by xivk** [comment]
I get these three routes using an uncontracted routerdb:

- http://geojson.io/#id=gist:anonymous/aa9d53f9cfcf7661308bbd6c3db75cd0&map=10/46.2516/14.6791
- http://geojson.io/#id=gist:anonymous/a561d9555389aa1415082ecf5894dfb4&map=12/46.3906/14.1765
- http://geojson.io/#id=gist:anonymous/2b793c38a5da6eeb1a80ddb14c9ee3fc&map=12/45.6713/15.1889

So it doesn't seem to be a data-issue. Testing some more now, will keep you informed.

**Comment by xivk** [comment]
I get these three when using a contracted routerdb:

- http://geojson.io/#id=gist:anonymous/a7efba694f92e82a179ba9d6b978b886&map=10/46.3306/14.8313
- http://geojson.io/#id=gist:anonymous/ad82fd4c0227abcf99bc58996274a499&map=10/46.1603/14.2754
- http://geojson.io/#id=gist:anonymous/420c616aa9ce33c9af6904a3e81c1d6b&map=10/45.8522/15.3795

This code was used:

```
            Itinero.Logging.Logger.LogAction = (o, level, message, parameters) =>
            {
                Console.WriteLine(string.Format("[{0}] {1} - {2}", o, level, message));
            };

            var routerDb = new RouterDb();

            using (var stream = File.OpenRead(@"path/to/slovenia-latest.osm.pbf"))
            {
                routerDb.LoadOsmData(stream, Itinero.Osm.Vehicles.Vehicle.Car);
            }
            routerDb.AddContracted(Itinero.Osm.Vehicles.Vehicle.Car.Fastest());

            var router = new Router(routerDb);
            var route = router.Calculate(Itinero.Osm.Vehicles.Vehicle.Car.Fastest(),
                new Coordinate(46.50853f, 15.07739f), new Coordinate(46.24624f, 14.35322f));
            route = router.Calculate(Itinero.Osm.Vehicles.Vehicle.Car.Fastest(),
                new Coordinate(46.43107f, 14.07973f), new Coordinate(45.88519f, 14.43405f));
            route = router.Calculate(Itinero.Osm.Vehicles.Vehicle.Car.Fastest(),
                new Coordinate(45.57986f, 15.19478f), new Coordinate(46.12383f, 15.57374f));
```

**Comment by alecava58** [comment]
Yes Ben I think the case is the same. I have ti finish the test but I think
that the exception happens also with not contracted db even if with
contracted the exception happens much more.

-- Alessandro

Il 06 gen 2017 09:19, "Ben Abelshausen" <notifications@github.com> ha
scritto:

**Comment by amarinsek** [comment]
Let me check something... plus, I will try to find shorter routes for easier examination.

**Comment by amarinsek** [comment]
I am still not sure but it looks like that problems were caused by my improper vehicle lua. No such errors if using only Itinero.Osm.Vehicles.Vehicle.
