### ISSUE TITLE
GenerateInstructions performance issue

### ISSUE THREAD

**Issue by amarinsek** [itinero/routing#57]
While route.Calculate(...) executes fast is route.GenerateInstructions() quite slow. I did not go into the code details, but it looks like that the cause is in Lua Interop. For example: 50 km route is calculated in 35 ms while GenerateInstructions takes 1150 ms.

Is it possible to speed up GenerateInstructions?

**Comment by xivk** [comment]
Probably this is due to the instructions being generated in the Lua scripts, I'll check to see if I can improve performance. 

What would definetly help is generating the instructions using plain C# but that should be a last resort option because it would defeat the purpose of dynamic vehicle profiles.

**Comment by anothar** [comment]
Hi, @xivk .Performance issues are definitely due to Lua scripts. I needed some speed-up for TryCalculate so I profiled this method. Excluding TryReolve time (as there is no easy speed up) Lua script call takes more than 50 percent of time

**Comment by xivk** [comment]
Yes, I know, not really a quick-fix solution, except the suggestion that what's now written in lua can also be done using C#. That should speed up things a lot.

**Comment by anothar** [comment]
Thx. I'll write car profile in C#.

**Comment by amarinsek** [comment]
@anothar I saw you have car profile in C#. What is the performance gain for GenerateInstructions?

**Comment by anothar** [comment]
Hi @amarinsek. Up to 100 times. Actually with car profile in C# it is counted in milliseconds. Here is [link](https://github.com/anothar/routing/tree/develop/src/Itinero.FastVehicle) to my C# car profile.

**Comment by xivk** [comment]
The routing profile gains will be extremely minimal because everything is pre-calculated, speed/factors/access per link type is calculated before routing starts so during routing the profiles are not touched anymore.

This is different in the instruction generation.

**Comment by xivk** [comment]
Closing this, I added to the roadmap for Itinero 2.0 to reevalute using lua for instruction generation or to fix the performance issues.

**Comment by xivk** [comment]
https://github.com/itinero/routing/wiki/Roadmap
