### ISSUE TITLE
Using external data

### ISSUE THREAD

**Issue by amarinsek** [itinero/routing#58]
I am wondering if there is a plugin/handler/know-how to integrate external data into the route calculation. There are two use cases:
a) use of external edge/vertice weight for optimal route calculation (for example FCD - floating car data)
b) use of external data in GenerateInstructions (for example location of toll stations and toll pricing)

**Comment by xivk** [comment]
No handler for now for floating car data sorry. This is something that is on the roadmap now:

https://github.com/itinero/routing/wiki/Roadmap (I assumed it was already there but it wasn't, so I just added it)

The generate instructions is customizable using the lua profiles, check here:

https://github.com/itinero/routing/wiki/Profiles

I'll try and add some instructions on how to add your own custom instructions but you will need to include some extra data to be able to handle toll stations/pricing. The current instruction generation code for cars for example is here:

https://github.com/itinero/routing/blob/develop/src/Itinero/Osm/Vehicles/car.lua#L227 (everything below that line)

**Comment by xivk** [comment]
@amarinsek Closing this issue, feel free to reopen if you need more info.
