### ISSUE TITLE
Exception in AddContracted()

### ISSUE THREAD

**Issue by TomQv** [itinero/routing#59]
The followint exception occurs when processing t4a-shp data:

System.IndexOutOfRangeException occurred
  HResult=-2146233080
  Message=Der Index war außerhalb des Arraybereichs.
  Source=Reminiscence
  StackTrace:
       bei Reminiscence.Arrays.MemoryArray`1.get_Item(Int64 idx)
       bei Itinero.Graphs.Directed.DirectedGraph.AddEdge(UInt32 vertex1, UInt32 vertex2, UInt32 data)
       bei Itinero.Graphs.Directed.DirectedMetaGraph.AddEdge(UInt32 vertex1, UInt32 vertex2, UInt32 data, UInt32 metaData)
       bei Itinero.Algorithms.Contracted.DirectedGraphBuilder`1.DoRun()
       bei Itinero.Algorithms.AlgorithmBase.Run()
       bei Itinero.RouterDbExtensions.AddContracted[T](RouterDb db, Profile profile, WeightHandler`1 weightHandler, Boolean forceEdgeBased)
       bei QmvCompiler.RoutableFromShp.Create(String qmrfile, String sourcefile) in C:\Users\Tom\QuoVadis\Qvm3\QvVecMap_Itinero\QmrShpCompiler\RoutableFromShp.cs:Zeile 36.
  InnerException:

**Comment by alecava58** [comment]
The same happens to me today when I'm trying to add a contracted profile to a routerdb that aready has another contracted profile (not the same that I'm trying to add).
I started from a not contracted routerdb adding both the profiles at the same time runs succesfully.
