### ISSUE TITLE
Itinero.IO.Osm is missing

### ISSUE THREAD

**Issue by pajaro5** [itinero/routing#6]
Hi

The nuget package does not include **Itinero.IO.Osm**

I just did 
`PM> Install-Package Itinero -IncludePrerelease`

![image](https://cloud.githubusercontent.com/assets/5140280/17338825/a3febc70-58ae-11e6-97ed-b55e247805d0.png)

**Comment by xivk** [comment]
Sorry, I should make this more clear in the docs, there are three packages:
- Itinero : The routing core.
- Itinero.IO.Osm : Preprocessing OSM data.
- Itinero.Geo : Links itinero with NTS geo package.

Reason for the split: no need to install all OSM and NTS dependencies when loading routingdb's from disk after preprocessing.

**Comment by pajaro5** [comment]
Thanks

Still I can't make it works,  I runed
`Install-Package OsmSharp -IncludePrerelease`
But the system its not able to find the method LoadOsmData
 
![image](https://cloud.githubusercontent.com/assets/5140280/17344164/d3367696-58c6-11e6-845a-161eda9fea73.png)

Thanks for your help.

**Comment by xivk** [comment]
What is the exact build error you are getting? Perhaps the arguments for LoadOsmData are incorrect?

**Comment by pajaro5** [comment]
The error says:
![image](https://cloud.githubusercontent.com/assets/5140280/17346887/6ededd76-58d2-11e6-83d1-2d708ab775c7.png)
The reference to the type "OsmGeo" confirms that it is defined in 'OsmSharp', but its not found.

I do not think its about the arguments because I am copying from the example detailed in the wiki.

**Comment by xivk** [comment]
Have you installed OsmSharp.Core? Should be installed along with the package but try updating it...

**Comment by pajaro5** [comment]
Hello

Finally I cloned the OsmSharp project and generate its DLL file,  so now I was able to run the sample using my own data.
I compared the results vs Google Maps and the distance calculated is reasonable.

**Comment by xivk** [comment]
@pajaro5 Can you tell me what went wrong. You shouldn't have to build OsmSharp manually...

**Comment by pajaro5** [comment]
Well basically the problem are the nuget packages...
