### ISSUE TITLE
Bicycle, can't find networks, or balanced 

### ISSUE THREAD

**Issue by t22dk** [itinero/routing#66]
Hi.

I am using the newest pre-release of Itinero, but can't find two of the profiles for bicycle.

I am trying to get this to work

 _bicycle vehicle: Also definas a default factor_and_speed function but in addition it defines two more:
balanced: Aggressively chooses bicycle-only parts of the network.
networks: Aggressifely chooses bicycle routing networks._

What could I be doing wrong ?

See the little video
[Video](https://www.screencast.com/t/oNsIAi3GdVza)

**Comment by xivk** [comment]
Cannot see the video, uses flash...

Perhaps the problem is that vehicles only explose fastest and shortest by default... try using this method:

https://github.com/itinero/routing/blob/develop/src/Itinero/Profiles/Vehicle.cs#L120

Also have al look at how Shortest() and Fastest() work...

**Comment by xivk** [comment]
ping @t22dk did this fix the issue?
