### ISSUE TITLE
Strange routing in NL

### ISSUE THREAD

**Issue by xivk** [itinero/routing#67]
Check these routes:

http://geojson.io/#id=gist:anonymous/7d029fecd8518de36bbbe48859fddf53&map=13/52.0885/5.0486 

Car.Shortest is not always correct, most likely an issue in the uncontracted routing.

**Comment by xivk** [comment]
Result is now:

http://geojson.io/#id=gist:anonymous/79d38e7ae740afbff64302731765e213&map=13/52.0925/5.0504

**Comment by RBroch** [comment]
Based on car.lua, shortest, contracted the route is not correct.
http://geojson.io/#id=gist:anonymous/f885598294824a0d45d50a71de02a301&map=13/52.0901/5.0480
