### ISSUE TITLE
RouteNotFound exception

### ISSUE THREAD

**Issue by alecava58** [itinero/routing#69]
Hi Ben,

sometime I'll get RouteNotFound exception and I don't know why. If you try with italy db using car profile and the following coordinates you will get a RouteNotFound Exception even if the TryResolveConnect returns ok.

How could I solve this problem?
`

            var router = new Router(routerDb);
            var lat = new double[] { 42.430149000000, 42.040694900000 };
            var lon = new double[] { 12.100029000000, 11.936966800000 };

            IList<RouterPoint> rp = new List<RouterPoint>();

            for (int i = 0; i < lat.Length; i++)
            {
                var r = router.TryResolve(profile, (float)lat[i], (float)lon[i], 100);
                if (r.IsError)
                    Console.WriteLine(string.Format("Error position: {0}", r.ErrorMessage));

                r = router.TryResolveConnected(profile, (float)lat[i], (float)lon[i], maxSearchDistance: 100);
                if (r.IsError)
                    Console.WriteLine(string.Format("Position not connected: {0}", r.ErrorMessage));

                rp.Add(r.Value);

            }

            var ret = router.TryCalculate(profile, rp.ToArray());
`

**Comment by Angelminster** [comment]
Same Here with Spain db

**Comment by alecava58** [comment]
@kevin-work do you need something else from my side?

**Comment by kevin-work** [comment]
@alecava58 Which line are you actually getting the exception?

**Comment by alecava58** [comment]
![image](https://cloud.githubusercontent.com/assets/1788993/22928522/311243aa-f2b7-11e6-8d3b-fe39817c2923.png)

can you see the image?

**Comment by alecava58** [comment]
This is the cycle that fails:
![image](https://cloud.githubusercontent.com/assets/1788993/22928799/92eedf6a-f2b8-11e6-9500-4f8724046915.png)

**Comment by kevin-work** [comment]
@alecava58 Which line is it happening in your code?

**Comment by xivk** [comment]
This is 99% sure this location that is in error. This however should he caught by ResolveConnected, will check what's going on there:

http://geojson.io/#id=gist:anonymous/1dfd4c8a71664b82c0feda16f5a4215d&map=18/42.04054/11.93726
