### ISSUE TITLE
Avoiding access based on a specific tag

### ISSUE THREAD

**Issue by alecava58** [itinero/routing#7]
Hi,

I'd like to set a specialized BigTruck vehicle avoiding access if the way or node has a specific tag (e: hazmat=no).
I've created a new class derived by BigTruck but I don't know which method to override.

can you help me?

Thanks in advance

**Comment by xivk** [comment]
First of all you need to make sure the tags you are going to use are not dropped. In the stream target loading the data you need to make sure tags are not normalized and that the profile indicates it wants the tags in by marking them as relevant:

https://github.com/itinero/routing/blob/develop/src/Itinero.IO.Osm/Streams/RouterDbStreamTarget.cs#L420

https://github.com/itinero/routing/blob/develop/src/Itinero.IO.Osm/Streams/RouterDbStreamTarget.cs#L430

In the profile you should be able to do what you want when you check the existing vehicles and profiles here:

https://github.com/itinero/routing/tree/develop/src/Itinero/Osm/Vehicles

Using node tags is unfortunately not possible at the moment without modifying the RouterDbStreamTarget and include these as restrictions.

**Comment by alecava58** [comment]
if I understand well ther is no need to modify anything in the core project. I should be able to do what I want only with vehicle profile, isn't it?

Thanks
Alessandro

**Comment by xivk** [comment]
Yes it should, if that's not possible then let me know. Also if you use tags not taken into account in the 'tag normalization' code you have to disable it when loading the OSM-data.

https://github.com/itinero/routing/blob/develop/src/Itinero/Osm/OsmRoutingTagNormalizer.cs

This drops all tags it doesn't know or rewrites them into an equivalent alternative.

**Comment by alecava58** [comment]
Ok. I'll try how you suggest.

Thanks
