### ISSUE TITLE
Can't read PBF files anymore

### ISSUE THREAD

**Issue by t22dk** [itinero/routing#72]
When using the latest build, it can not read denmark.latest.pbf

`routerDb.LoadOsmData(stream, Vehicle.Car);`

```
An exception of type 'System.MissingMethodException' occurred in OsmSharp.dll but was not handled in user code

Additional information: Method not found: System.Nullable1<Single> OsmSharp.Node.get_Latitude().
```

**Comment by xivk** [comment]
Did you update OsmSharp? You are probably using v6.x... try using v5.0.6 stable.

**Comment by t22dk** [comment]
You are right. 

Using 5.0.6 fixed it.
