### ISSUE TITLE
Question: From gpx file to route/instructions?

### ISSUE THREAD

**Issue by bertt** [itinero/routing#80]
Hi, Is there an option/sample for creating route/instructions from an existing gpx?

**Comment by xivk** [comment]
That would be non-trivial, it would mean doing map-matching. After that you could build a route and then generate instructions.

The map-matching part is not implemented yet. This kind of development on Itinero is my day job... ;-)

**Comment by bertt** [comment]
ok clear thanks!

**Comment by xivk** [comment]
ok, let me know if you need anything else, map matching is on the roadmap but probably won't happen for a couple of months.
