### ISSUE TITLE
Deserialized DB is Readonly(EdgeMeta)

### ISSUE THREAD

**Issue by anothar** [itinero/routing#81]
Hi Ben. In my tests I use data from OSM. To speed up loading I tried to use serialized version of RouterDb.
But the problem is that I should modify data. Unfortunately when I try to modify RouterDb it throws exception that EdgeMeta is in ReadOnly state. So the question is how to deseralize RouterDb keeping possibility to change data?

**Comment by xivk** [comment]
No, that's not possible at the moment. What you could do is create a new AttributeIndex and copy things over.

I'm not sure anymore why the attribute index becomes readonly, probably just because the usecase of adding attributes after the routerdb was serialized never came up... I would need to investigate to make sure but perhaps it's possible to change it after deserialization but I'm not sure.

You can always look at the code here:

https://github.com/itinero/routing/blob/develop/src/Itinero/Attributes/AttributesIndex.cs

**Comment by anothar** [comment]
Thx Ben. I have one more question: what is branch? I saw property Bransches in route but I can't understand what is it for?

**Comment by xivk** [comment]
To be able to generate turn-by-turn instructions a route also needs 'branches'. These are the streets that are not used at intersections for example. An example, blue is the route, red the branches:

http://geojson.io/#id=gist:anonymous/e41979ef18d6d2643ebed96d941eca5f&map=17/51.26860/4.79938

**Comment by xivk** [comment]
Did you find another solution?

**Comment by anothar** [comment]
No. Unfortunately I was unable to create writable copy of RouterDb. I got stuck on AttributesIndex, It occured that it's impossible to clone right because all Reminiscence collections are readonly. And IndexMode is not saved during serialization-deserialization.

**Comment by xivk** [comment]
What's your usecase maybe I can help. Perhaps there is another way...

**Comment by anothar** [comment]
Well I just wanted my test data from OSM to load a little faster. But now I realized that my code is taking much more time than OSM loading. So I postponed OSM loading speedup as it's not critical.

Regardinbg usecase. I have to add some additional data which is not contained in OSM. And I test it in conjunction with OSM data.

**Comment by xivk** [comment]
There is an option to add a 'filter' to the source stream, you can change the tags of the OSM-ways when they are loading.

**Comment by xivk** [comment]
Closing issue, AttributesIndex will remain readonly for now, the idea is to add all the needed data at startup. 

This could be a future usecase of this: https://github.com/itinero/routing/issues/103
