### ISSUE TITLE
Route Not Found Exception again

### ISSUE THREAD

**Issue by alecava58** [itinero/routing#82]
Hi Ben, after the last fix I have the Route Not Found Exception using the following coordinates:

            var lat = new double[] { 45.516299, 45.455271 };
            var lon = new double[] { 9.0116221, 9.180606 };

**Comment by xivk** [comment]
There was a bug, the first edge of the resolved point was not properly checked for access when doing a connected resolve. On top of that I did need to increase the defaults again (2000m / 200m) but you probably already do that:

`
var point2 = router.ResolveConnected(Itinero.Osm.Vehicles.Vehicle.Car.Fastest(), 45.455271f, 9.1806060f, 2000, 200);
`

**Comment by xivk** [comment]
Thanks again for catching this one 👍

**Comment by alecava58** [comment]
Thanks for the quick fix.
