### ISSUE TITLE
question: change access_value on lua profile

### ISSUE THREAD

**Issue by alecava58** [itinero/routing#88]
I have a route that ends to a private road. The destination is on a private road.
With the standard car profile you cannot access road marked as "private", so the routing fails.
I changed the car lua profile setting private road as accessible.
Using the modified lua profile on the fly (loading it with dynamic vehicle), without rebuilding router db, the routing still fails.
Must I rebuild the router db when I change the lua's access_values?

**Comment by xivk** [comment]
You shouldn't have to when the correct tags are there but it's possible your modification changed a bit the processing of the data so in that case, yes you should rebuild the routerdb.

Some profile changes won't have to impact, some will. It's best to rebuild.

**Comment by alecava58** [comment]
I've rebuild the router db but the exception "route not found" is still there. If I move the destination to the nearest not private road the routing is ok.

**Comment by xivk** [comment]
Can you give me the location? I also recently added this extension method to make debugging easier:

https://github.com/itinero/routing/blob/develop/src/Itinero/RouterDbExtensions.cs#L576

If you do this, and send the geojson perhaps there is some way to see what's happening. Also include your modified lua profile.

**Comment by alecava58** [comment]
The locations are:

            var lat = new double[] { 46.0553251, 46.4606823 };
            var lon = new double[] { 11.2341531, 11.7054686 };

I'm using Italy db not contracted and a car lua profile as atatched (it is a standard lua profile with ["private"] = true).
 
if you try;

            IList<Coordinate> coo = new List<Coordinate>();
            for (var i = 0; i < lat.Length; i++)
                coo.Add(new Coordinate((float)lat[i], (float)lon[i]));
            ret = router.TryCalculate(prof, coo.ToArray());

you'll get:
"Could not resolve point at [46.46068, 11.70547]. Probably too far from closest road or outside of the loaded network."

if you try:


            IList<RouterPoint> rp = new List<RouterPoint>();
            for (int i = 0; i < lat.Length; i++)
            {
                var r = router.TryResolveConnected(localVehicle.Profile("shortest"), (float)lat[i], (float)lon[i]);
                if (r.IsError)
                    r = router.TryResolveConnected(localVehicle.Profile("shortest"), (float)lat[i], (float)lon[i], radiusInMeter: 2000, maxSearchDistance: 1000);
                if (r.IsError)
                    Console.WriteLine(string.Format("Position not connected: {0}", r.ErrorMessage));

                rp.Add(r.Value);
            }
            ret = router.TryCalculate(prof, rp.ToArray());



you'll get:
'ret.Value' threw an exception of type 'Itinero.Exceptions.RouteNotFoundException'

What I saw (if I don't make a mistake) is that the second TryResolveConnected calculates a coordinates that are in the opposite direction than the nearest routable road.
[geojson.txt](https://github.com/itinero/routing/files/857599/geojson.txt)

[car.lua.txt](https://github.com/itinero/routing/files/857606/car.lua.txt)

**Comment by alecava58** [comment]
I changed the car lua profile setting access_value ["private"] = true.
I rebuilt the router db using that profile.
I tried to calculate route using that profile.
Still have "route not found exception".

**Comment by xivk** [comment]
This could be due to https://github.com/itinero/routing/issues/96

**Comment by alecava58** [comment]
Solved using the solution #85
