### ISSUE TITLE
Route Builder doesn't return correct start and endpoints

### ISSUE THREAD

**Issue by xivk** [itinero/routing#90]
A bug was introduced by this commit:

https://github.com/itinero/routing/commit/332571a07f06296d7a2d999deeb64e46e2f721c6

It changes the lat/lon in the routerpoint to the original requested location, not the resolved location as it should. The route builder however assumes incorrectly that the routerpoint contains the resolved lat/lon. This produces a strange effect at start or end when the start or endpoint aren't perfectly on a road when resolved.

**Comment by t22dk** [comment]
Yep, I was about to make a bug about this.

And I think that your description is spot on :-)
