### ISSUE TITLE
[Question] Edge-Based Contraction: Performance and Tradeoffs?

### ISSUE THREAD

**Issue by airbreather** [itinero/routing#91]
Just looking to talk about the performance of edge-based contraction a little bit here.

I've been looking to speed up contraction hierarchy building, using a planet.osm PBF source (well, a full RouterDb instance, not the original OSM file, since I can build a RouterDb quickly enough).  I've been focusing primarily on the edge-based contraction for obvious reasons.  My progress so far is on [my fork's perf-experimental branch](https://github.com/airbreather/routing/tree/perf-experimental).  I've gotten some pretty significant improvements so far, with my Core i7-6850k machine reaching the first `HierarchyBuilder<float>.CalculateQueue` call in 90 seconds and the first `HierarchyBuilder<float>.SelectNext` call in about 5.5 minutes, both counting from the start of the "Itinero.Build" application in that fork (when the full routerdb file is already cached in memory by the OS).  For comparison, the regular ol' Reminiscence `MemoryArray<T>` implementation takes over 2 minutes just to finish the `RouterDb.Deserialize` call, and `HierarchyBuilder<float>.CalculateQueue` was... a lot longer (I don't remember right now).

But I'm a little bit stuck when it comes to how to optimize the actual priority calculator and the witness calculator, so I'd like to see if I can pick your brain for a few details, and also maybe check in to see if you're already looking into some of these things.

Context: I'm looking to see how fast I can make the whole process from "get latest planet.osm.pbf" to "enjoy fast travel time / distance calculations".  This is just a fun side project for me right now, but I'd like to bring it into work and have us seriously weigh costs and benefits of a matrix of "Itinero vs. expensive proprietary solution" and "OSM vs. TeleAtlas".  Right now, as you might imagine, at work we're on the "expensive proprietary solution + TeleAtlas" quadrant of that matrix, and (shocking surprise incoming) there are forces within the company that would like to switch to the less expensive "Itinero + OSM" quadrant if it's going to be of comparable quality.  We buy TeleAtlas data for various regions of the world, and in some places we use other sources for travel calculations, so it would be nice if we could centralize the data and processing in one place to leverage worldwide (look at me talking all business-like...).  Our proprietary stuff also takes quite a while and lots of manpower to get from the TeleAtlas sources to something usable, so cutting down on that lead time would be a big deal too.

For now, though, I'd just like to get a better feel for where Itinero is and what can be done.

1. Would `HierarchyBuilder<float>` benefit significantly from a good `RemoveWitnessedEdges` implementation?  I've tried out node-based contraction on the same data set, and I've actually seen it finish... I'm guessing that its version of `RemoveWitnessedEdges` does a lot to speed up the lazy updating step.  I see an earlier attempt to make this happen, but I'm guessing that the restrictions made it too complicated.
2. It looks like setting `DykstraWitnessCalculator<T>`'s `_hopLimit` / `_maxSettles` to smaller values would speed up the initial one-off processing time; how much of an impact would this have on the calculations that happen afterward?  I see that node-based contraction with the default parameters (per `RouterDbExtensions.AddContracted<T>`) just goes all-in with `int.MaxValue`, and it finishes just fine even for the whole planet, but the restrictions seem to really complicate the other side of things.
3. Do you see any avenues where `HierarchyBuilder<T>` can make use of multi-core systems to speed up processing different parts of the network, without affecting the correctness of the end results?  I've already got `HierarchyBuilder<T>.CalculateQueue` running parallel calls to `_priorityCalculator.Calculate` since it's just calculating the independent priority of each vertex, but I don't see an obvious "mechanical" way to do a similar thing with the next bottleneck, because of the data dependencies.  Purely conceptually, though, wouldn't it be **possible** to start one thread at the north pole, one thread at the south pole, and have them both work their way toward the equator, flagging anything that could potentially have a path that crosses the equator, and then have another thread just dealing with the flagged things?  Obviously if this could work, then it could be sub-divided even further, kinda like Merge Sort, just splitting the calculation up until reaching a point where it's typically not beneficial to split anymore.
4. Are you already working on any other things that might make this part of the process faster, and so I shouldn't bother?

**Comment by xivk** [comment]
Perhaps we should start a slack channel or something similar to discuss this, it's awesome you want to help with this, there is a lot to be considered, so this perhaps calls for another way of communicating... ;-)

**Comment by airbreather** [comment]
Sounds like a good idea.  I've never used Slack before.  I could also use IRC, I'm on freenode (I just made a new #itinero channel).

Or just e-mail me to set it up, it's my GitHub username at linux dot com (same as the e-mail I use for my public Git commits).

**Comment by xivk** [comment]
I'm on IRC now, not a lot of time today but we can discuss there...

**Comment by xivk** [comment]
Edge-base contraction performance should be better now since april but if you're still interested in implementing some of the other idea's in this issue let me know.

> Context: I'm looking to see how fast I can make the whole process from "get latest planet.osm.pbf" to "enjoy fast travel time / distance calculations". This is just a fun side project for me right now, but I'd like to bring it into work and have us seriously weigh costs and benefits of a matrix of "Itinero vs. expensive proprietary solution" and "OSM vs. TeleAtlas". Right now, as you might imagine, at work we're on the "expensive proprietary solution + TeleAtlas" quadrant of that matrix, and (shocking surprise incoming) there are forces within the company that would like to switch to the less expensive "Itinero + OSM" quadrant if it's going to be of comparable quality. We buy TeleAtlas data for various regions of the world, and in some places we use other sources for travel calculations, so it would be nice if we could centralize the data and processing in one place to leverage worldwide (look at me talking all business-like...). Our proprietary stuff also takes quite a while and lots of manpower to get from the TeleAtlas sources to something usable, so cutting down on that lead time would be a big deal too.

=> I'm also available to consult with your company to make this transition

Closing this because work on customizable CH's is going to start, any further performance improvement will have to made in that new code.
