### ISSUE TITLE
Introduce a struct that represents a directed edge id.

### ISSUE THREAD

**Issue by xivk** [itinero/routing#95]
Introduce a struct that represents a directed edge id. 

#### Motivation:

Now there are two types:

- _edgeid_: an undirected id, _uint_ representing an edge without a direction.
- _directededgeid_: a directed id, _long_ representing and edge including it's direction.

The first one is used to refer to an edge internally, the second one is use in path descriptions and to provide direction whenever referring to an edge. 

The relation between an _edgeid_and _directededgeid_:

- forward: _directededgeid_= _edgeid_+ 1
- backward: _directededgeid_= -_edgeid_- 1

Currently it's possible to use an _edgeid_ as a _directededgeid_ without any issue because of the implicit conversion between _uint_ and _long_. This can cause strange errors and routes that make no sense without Itinero being able to catch these mistakes.

#### Proposed changes:

Introduce a struct that represents a _directededgeid_ with helper methods to convert from/to _edgeid_ using a direction flag.

**Comment by Mehdib64** [comment]
Following the suggestion, is there anyway to get an edge (start, end and coordinate) using its (long)directedEdgeid? I could find the one for undirected one but need to retrive the directed one.
cheers

**Comment by xivk** [comment]
Yes, you can just do

if directededgeid < 0: edgeid = -directededgeid -1
else edgeid = directededgeid - 1

A directededgeid of '0' makes no sense.

This is exactly what this issue is trying to fix, it's not very clear at the moment what's what. But it's a pretty big breaking change so it will have to wait for 2.0.

**Comment by xivk** [comment]
This struct has been added, closing this issue until work is started on 2.0. Added this to the roadmap:

http://docs.itinero.tech/docs/itinero/development/index.html
